### ISSUE TITLE
The form for a new feature doesn't display the "submit" button

### ISSUE THREAD

**Issue by yoavweiss** [GoogleChrome/chromium-dashboard#1001]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
I started filing a new feature status, and the initial screen didn't show me any submit button. As a result, I tracked the submit button in devtools, and "clicked" submit through the console.

**To Reproduce**
1. Go to chromestatus 
2. Click on "add a new feature"
3. Look for the submit button

**Expected behavior**
I expected to find the submit button

**Additional context**

**Comment by jrobbins** [comment]
What does the feature entry page look like for you?  Can you share a screenshot?

It should look like this:
https://screenshot.googleplex.com/63fgcwqzEeB3Gfq

**Comment by yoavweiss** [comment]
https://ibb.co/dLM1bbn
My viewport height is 936 pixels

**Comment by jrobbins** [comment]
Thanks for reporting that.  The floating footer has always annoyed me, so it is good to have a concrete bug report about it from a user.  I have a large local draft CL for a visual refresh that includes changing the footer to be laid out at the bottom of the page content rather than trying to have app-like position:fixed.  I'm planning on deploying that fix by Sept 14.

**Comment by yoavweiss** [comment]
Yay!! :)

**Comment by jrobbins** [comment]
The floating footer is gone now.  There should be nothing covering up any submit buttons.
