### ISSUE TITLE
Research which data storage backend to use

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1075]

**Comment by shivamag00** [comment]
Because of my limited experience, I am unaware with the term `data storage backend`. Hence, I assume that it means database. If this assumption is wrong, please let me know.

Just for the record, I am aware that as a pre-requisite to Python 3 upgrade, we need to replace our use of DB Client Library for accessing Cloud DataStore as mentioned in this Google Cloud [guide](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrate-to-cloud-ndb)
 
May we work on this issue, @jrobbins ?

**Comment by shivamag00** [comment]
This [link](https://cloud.google.com/datastore/docs/upgrade-to-firestore) says that all `Datastore` instances will be gradually updated to `Firestore in Datastore` Mode starting this year. 

Also, this [link](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrate-to-cloud-ndb#key_differences) suggests that there are only minor syntax changes between App Engine NDB (we are using DB Client Library.  App Engine NDB was an improvement over DB Client Library) and Cloud NDB (for accessing Firestore in Datastore Mode). The link also lists the major differences between the two.

**Comment by shivamag00** [comment]
@jrobbins, please let me know what other options for storage backend we can consider.

**Comment by jrobbins** [comment]
I think that this is the most practical upgrade path and that your PRs are on the right track.  Let's consider the research part of this work finished.
