### ISSUE TITLE
'Experimental Timeline' field can't be edited

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1176]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The end of the origin trial was moved for this: https://www.chromestatus.com/feature/5702310124584960

The 'Experimental Timeline' field can't be updated to match.
![image](https://user-images.githubusercontent.com/8204171/108415384-53f45080-71e2-11eb-8e4e-7d91a7c150a2.png)

**To Reproduce**
1. Go to the Origin Trial stage
2. Try to clicked in the field just named.

**Expected behavior**
I should be able to edit the field.

**Additional context**
Do we even need this field. It duplicates the milestone fields, but without data validation.

**Comment by jrobbins** [comment]
The "experimental timeline" field was the old field that was used before we added the specific start and end fields.  It is only shown for features that had that old field filled in before we added the new fields.  I wanted to show it as a reference so that old information was not lost.   But, I could see how it could be confusing if it contradicts the values shown in the other fields.

How about only showing a read-only "Experimental timeline" field when the start and end fields are blank?  If either of those is filled in, then we could hide the "Experimental timeline" field on that feature.

**Comment by jpmedley** [comment]
Can it be hidden on new entries so we don't have this problem in the future?

**Comment by jpmedley** [comment]
>How about only showing a read-only "Experimental timeline" field when the start and end fields are blank? If either of those is filled in, then we could hide the "Experimental timeline" field on that feature.

That would work. Please make sure you check the display forms too.

![image](https://user-images.githubusercontent.com/8204171/109669292-d0fac080-7b26-11eb-970d-da934101a344.png)

**Comment by jpmedley** [comment]
We fixed this, but I don't known when.
