### ISSUE TITLE
Paginate the "All features" list

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1196]
**Describe the solution you'd like**
Rather than the current single huge page of "All features", we should present a paginated list of, say, 100 feature entries at a time with "Next" and "Prev" links to move among pages.

The reason for this change is to make the site more scalable.  As the number of feature entries in our database has grown, displaying a huge list already became unmanageable.   We already capped the length of the list with no way to navigate to later items without narrowing the search terms, which is not ideal.  Also, relying on a single huge JSON feed is not scalable.

**Additional context**
We should retain the existing /features_v2.json feed for use by outsiders who have dependencies on it.

We should define a new JSON API handler for getting a feature list and have the frontend call that instead.  The new handler would include pagination start index or continuation token.  In the future we might add search terms for server-side filtering, sorting options, and grouping options. This API handler would return significantly less information for each feature entry than the JSON feed does.

**Comment by CrypticWizard** [comment]
@jrobbins I wanted some advice here.

Since we are utilising the DB Client library, pagination can be implemented with [Query Cursors](https://cloud.google.com/appengine/docs/standard/python/datastore/query-cursors) in the new API which allows extraction of query results in batches. But the problem is, this library is [no longer recommended](https://cloud.google.com/appengine/docs/standard/python/datastore/queries). How to go ahead with this?  TIA

**Comment by shivamag00** [comment]
As a pre-requisite to Python 3 upgrade, we have to replace our use of DB Client Library ( compatible with Python 2 only ) with some other library that is compatible with both Python 2 and Python 3. Hence, you may like to follow #1075 and #1076.

**Comment by shivamag00** [comment]
We have a search-box in the frontend which uses JS for searching. Hence, we need to re-implement it in a way such that it can search through all the results even after pagination is implemented. This must be done before pagination is implemented otherwise the search-box will not function properly resulting in poor UX.

**Comment by past** [comment]
This is now done.
