### ISSUE TITLE
Not able to set up local dev env

### ISSUE THREAD

**Issue by codereverma** [GoogleChrome/chromium-dashboard#1198]
**Describe the bug**
I followed the entire guide from README about local setup but was not able to get it running. Firstly node-sass was not mentioned in dependencies which was throwing intial errors in gulp. I manually installed that.

But after that I am not able to run the dev server due to some missing python dependencies which I tried installing both on local as well global scope. But still no luck. 

If possible can you help me with the setup or include missing dependencies in the code. 

I have attached the relevant logs here.

<pre><font color="#8AE234"><b>anurag@debian</b></font>:<font color="#729FCF"><b>~/chromium-dashboard</b></font>$ npm start

&gt; chromestatus-dashboard@ start /home/anurag/chromium-dashboard
&gt; npm run build &amp;&amp; ./scripts/start_server.sh

&gt; chromestatus-dashboard@ build /home/anurag/chromium-dashboard
&gt; gulp

[<font color="#555753">17:50:52</font>] Requiring external module <font color="#75507B">@babel/register</font>
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[<font color="#555753">17:50:57</font>] Using gulpfile <font color="#75507B">~/chromium-dashboard/gulpfile.babel.js</font>
[<font color="#555753">17:50:57</font>] Starting &apos;<font color="#06989A">default</font>&apos;...
[<font color="#555753">17:50:57</font>] Starting &apos;<font color="#06989A">clean</font>&apos;...
[<font color="#555753">17:50:57</font>] Finished &apos;<font color="#06989A">clean</font>&apos; after <font color="#75507B">153 ms</font>
[<font color="#555753">17:50:57</font>] Starting &apos;<font color="#06989A">styles</font>&apos;...
[<font color="#555753">17:51:02</font>] Finished &apos;<font color="#06989A">styles</font>&apos; after <font color="#75507B">5.28 s</font>
[<font color="#555753">17:51:02</font>] Starting &apos;<font color="#06989A">js</font>&apos;...
[<font color="#555753">17:51:05</font>] Finished &apos;<font color="#06989A">js</font>&apos; after <font color="#75507B">2.8 s</font>
[<font color="#555753">17:51:05</font>] Starting &apos;<font color="#06989A">lint-fix</font>&apos;...
[<font color="#555753">17:51:10</font>] Finished &apos;<font color="#06989A">lint-fix</font>&apos; after <font color="#75507B">5.46 s</font>
[<font color="#555753">17:51:10</font>] Starting &apos;<font color="#06989A">rollup</font>&apos;...
[<font color="#555753">17:51:31</font>] Finished &apos;<font color="#06989A">rollup</font>&apos; after <font color="#75507B">21 s</font>
[<font color="#555753">17:51:31</font>] Finished &apos;<font color="#06989A">default</font>&apos; after <font color="#75507B">34 s</font>
INFO     2021-03-11 12:21:39,931 devappserver2.py:289] Skipping SDK update check.
WARNING  2021-03-11 12:21:40,331 simple_search_stub.py:1198] Could not read search indexes from /tmp/appengine.cr-status.anurag/search_indexes
INFO     2021-03-11 12:21:40,333 api_server.py:282] Starting API server at: http://localhost:38807
INFO     2021-03-11 12:21:42,683 dispatcher.py:267] Starting module &quot;default&quot; running at: http://localhost:8080
INFO     2021-03-11 12:21:42,903 dispatcher.py:267] Starting module &quot;notifier&quot; running at: http://localhost:8081
INFO     2021-03-11 12:21:42,904 admin_server.py:150] Starting admin server at: http://localhost:8000
Traceback (most recent call last):
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py&quot;, line 96, in &lt;module&gt;
    _run_file(__file__, globals())
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py&quot;, line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py&quot;, line 206, in &lt;module&gt;
    main()
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py&quot;, line 177, in main
    sandbox.enable_sandbox(config)
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py&quot;, line 317, in enable_sandbox
    THIRD_PARTY_C_MODULES.get_importable_module_names(config))
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py&quot;, line 867, in __init__
    dep_lib = __import__(dep_lib_name)
ImportError: No module named enum
Traceback (most recent call last):
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py&quot;, line 96, in &lt;module&gt;
    _run_file(__file__, globals())
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py&quot;, line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py&quot;, line 206, in &lt;module&gt;
    main()
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py&quot;, line 177, in main
    sandbox.enable_sandbox(config)
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py&quot;, line 317, in enable_sandbox
    THIRD_PARTY_C_MODULES.get_importable_module_names(config))
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py&quot;, line 867, in __init__
    dep_lib = __import__(dep_lib_name)
ImportError: No module named enum
ERROR    2021-03-11 12:21:46,786 instance.py:284] Cannot connect to the instance on localhost:17542
ERROR    2021-03-11 12:21:46,981 instance.py:284] Cannot connect to the instance on localhost:16646
</pre>

I also found out the code is pretty much outdated and relies on a lot of vulenrable dependencies. I want to help in transitioning to python3.

**Comment by jrobbins** [comment]
You are correct that we are currently stuck on python2 and trying to work through a long-overdue update.  It's a big problem and your help is appreciated.

I'm able to run the app locally (and of course it is running on app engine on the live site, and in Travis CI) by using the GAE SDK for Python 2.7.  When you download the GAE SDK, make sure that you select "2.7", which will take you to this page:
https://cloud.google.com/appengine/docs/standard/python/setting-up-environment

I haven't reproduced the error that you see, but I am hoping that it would get you past the "enum" error.  There are other errors to work through after that one, maybe you can help solve them.

**Comment by CrypticWizard** [comment]
I also faced the "enum" error while starting the server with the exact same log as @codereverma but was able to work through it. The error is possibly caused by improper Cloud SDK setup or if it was installed with apt. The latter is highly likely.

The Cloud SDK component manager only works if you don't install the SDK through another package manager. The issue has been discussed [here](https://stackoverflow.com/questions/42697026/install-google-cloud-components-error-from-gcloud-command). 

The workaround is to remove the previosuly installed google-cloud-sdk first using `sudo apt purge --autoremove google-cloud-sdk`. Install Cloud SDK manually using the correct `.tar.gz` file listed [here](https://cloud.google.com/sdk/docs/install#linux). Follow the instructions under the **Linux** tab. Finally, execute `gcloud components install app-engine-python`  to install the app-engine-python. This resolved the "enum" error for me. All this was done in the global scope.

But, following this another error occured with npm start:
**./scripts/start_server.sh: line 10: dev_appserver.py: command not found**
Can anyone help with this?

**Comment by CrypticWizard** [comment]
I'm also stuck at the "enum" error. Is there any way out?

**Comment by whoanuragverma** [comment]
@codereverma You are facing this issue because you've not installed app-engine-sdk properly. I followed the documentation and was able to start the dev server.

However, when I visit localhost:8080 `no module named jinja2.tests` error is thrown and I get localhost is currently unable to handle this request. 
I manually installed Jinja2 at both local and global scope and even tried modifying inside app-engine-sdk but no luck.

I have attached the logs here. Please help me fix this. 

<pre>INFO     2021-03-13 13:46:19,736 devappserver2.py:289] Skipping SDK update check.
INFO     2021-03-13 13:46:20,107 api_server.py:282] Starting API server at: http://localhost:36335
INFO     2021-03-13 13:46:20,754 dispatcher.py:267] Starting module &quot;default&quot; running at: http://localhost:8080
INFO     2021-03-13 13:46:21,068 dispatcher.py:267] Starting module &quot;notifier&quot; running at: http://localhost:8081
INFO     2021-03-13 13:46:21,069 admin_server.py:150] Starting admin server at: http://localhost:8000
INFO     2021-03-13 13:46:25,878 instance.py:294] Instance PID: 21543
INFO     2021-03-13 13:46:26,124 instance.py:294] Instance PID: 21545
ERROR    2021-03-13 13:46:29,028 wsgi.py:269] 
Traceback (most recent call last):
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py&quot;, line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py&quot;, line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py&quot;, line 85, in LoadObject
    obj = __import__(path[0])
  File &quot;/home/anurag/chromium-dashboard/server.py&quot;, line 25, in &lt;module&gt;
    import common
  File &quot;/home/anurag/chromium-dashboard/common.py&quot;, line 29, in &lt;module&gt;
    import flask
  File &quot;/home/anurag/chromium-dashboard/lib/flask/__init__.py&quot;, line 14, in &lt;module&gt;
    from jinja2 import escape
  File &quot;/home/anurag/chromium-dashboard/lib/jinja2/__init__.py&quot;, line 12, in &lt;module&gt;
    from .environment import Environment
  File &quot;/home/anurag/chromium-dashboard/lib/jinja2/environment.py&quot;, line 25, in &lt;module&gt;
    from .defaults import BLOCK_END_STRING
  File &quot;/home/anurag/chromium-dashboard/lib/jinja2/defaults.py&quot;, line 4, in &lt;module&gt;
    from .tests import TESTS as DEFAULT_TESTS  # noqa: F401
  File &quot;/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py&quot;, line 1168, in load_module
    raise ImportError(&apos;No module named %s&apos; % fullname)
ImportError: No module named jinja2.tests
INFO     2021-03-13 13:46:29,055 module.py:865] default: &quot;GET / HTTP/1.1&quot; 500 -</pre>

**Comment by shivamag00** [comment]
@whoanuragverma @jrobbins, I am getting the same error. The `tests.py` file exists inside the `lib/jinja2` folder. However, due to some strange error, `defaults.py` inside the `lib/jinja2` cannot import `tests.py` located in the same directory

**Comment by shivamag00** [comment]
There is a temporary fix though... Since, `defaults.py` could not import from `tests.py`, I copied the complete code inside `tests.py` to `defaults.py`. This is what the complete code of `defaults.py` looks like now - 

`# -*- coding: utf-8 -*-
from ._compat import range_type
from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
# from .tests import TESTS as DEFAULT_TESTS  # noqa: F401
from .utils import Cycler
from .utils import generate_lorem_ipsum
from .utils import Joiner
from .utils import Namespace

# Added Code of tests.py
import decimal
import operator
import re

from ._compat import abc
from ._compat import integer_types
from ._compat import string_types
from ._compat import text_type
from .runtime import Undefined

number_re = re.compile(r"^-?\d+(\.\d+)?$")
regex_type = type(number_re)
test_callable = callable


def test_odd(value):
    """Return true if the variable is odd."""
    return value % 2 == 1


def test_even(value):
    """Return true if the variable is even."""
    return value % 2 == 0


def test_divisibleby(value, num):
    """Check if a variable is divisible by a number."""
    return value % num == 0


def test_defined(value):
    """Return true if the variable is defined:

    .. sourcecode:: jinja

        {% if variable is defined %}
            value of variable: {{ variable }}
        {% else %}
            variable is not defined
        {% endif %}

    See the :func:`default` filter for a simple way to set undefined
    variables.
    """
    return not isinstance(value, Undefined)


def test_undefined(value):
    """Like :func:`defined` but the other way round."""
    return isinstance(value, Undefined)


def test_none(value):
    """Return true if the variable is none."""
    return value is None


def test_boolean(value):
    """Return true if the object is a boolean value.

    .. versionadded:: 2.11
    """
    return value is True or value is False


def test_false(value):
    """Return true if the object is False.

    .. versionadded:: 2.11
    """
    return value is False


def test_true(value):
    """Return true if the object is True.

    .. versionadded:: 2.11
    """
    return value is True


# NOTE: The existing 'number' test matches booleans and floats
def test_integer(value):
    """Return true if the object is an integer.

    .. versionadded:: 2.11
    """
    return isinstance(value, integer_types) and value is not True and value is not False


# NOTE: The existing 'number' test matches booleans and integers
def test_float(value):
    """Return true if the object is a float.

    .. versionadded:: 2.11
    """
    return isinstance(value, float)


def test_lower(value):
    """Return true if the variable is lowercased."""
    return text_type(value).islower()


def test_upper(value):
    """Return true if the variable is uppercased."""
    return text_type(value).isupper()


def test_string(value):
    """Return true if the object is a string."""
    return isinstance(value, string_types)


def test_mapping(value):
    """Return true if the object is a mapping (dict etc.).

    .. versionadded:: 2.6
    """
    return isinstance(value, abc.Mapping)


def test_number(value):
    """Return true if the variable is a number."""
    return isinstance(value, integer_types + (float, complex, decimal.Decimal))


def test_sequence(value):
    """Return true if the variable is a sequence. Sequences are variables
    that are iterable.
    """
    try:
        len(value)
        value.__getitem__
    except Exception:
        return False
    return True


def test_sameas(value, other):
    """Check if an object points to the same memory address than another
    object:

    .. sourcecode:: jinja

        {% if foo.attribute is sameas false %}
            the foo attribute really is the `False` singleton
        {% endif %}
    """
    return value is other


def test_iterable(value):
    """Check if it's possible to iterate over an object."""
    try:
        iter(value)
    except TypeError:
        return False
    return True


def test_escaped(value):
    """Check if the value is escaped."""
    return hasattr(value, "__html__")


def test_in(value, seq):
    """Check if value is in seq.

    .. versionadded:: 2.10
    """
    return value in seq


DEFAULT_TESTS = {
    "odd": test_odd,
    "even": test_even,
    "divisibleby": test_divisibleby,
    "defined": test_defined,
    "undefined": test_undefined,
    "none": test_none,
    "boolean": test_boolean,
    "false": test_false,
    "true": test_true,
    "integer": test_integer,
    "float": test_float,
    "lower": test_lower,
    "upper": test_upper,
    "string": test_string,
    "mapping": test_mapping,
    "number": test_number,
    "sequence": test_sequence,
    "iterable": test_iterable,
    "callable": test_callable,
    "sameas": test_sameas,
    "escaped": test_escaped,
    "in": test_in,
    "==": operator.eq,
    "eq": operator.eq,
    "equalto": operator.eq,
    "!=": operator.ne,
    "ne": operator.ne,
    ">": operator.gt,
    "gt": operator.gt,
    "greaterthan": operator.gt,
    "ge": operator.ge,
    ">=": operator.ge,
    "<": operator.lt,
    "lt": operator.lt,
    "lessthan": operator.lt,
    "<=": operator.le,
    "le": operator.le,
}

# Code of tests.py ends














# defaults for the parser / lexer
BLOCK_START_STRING = "{%"
BLOCK_END_STRING = "%}"
VARIABLE_START_STRING = "{{"
VARIABLE_END_STRING = "}}"
COMMENT_START_STRING = "{#"
COMMENT_END_STRING = "#}"
LINE_STATEMENT_PREFIX = None
LINE_COMMENT_PREFIX = None
TRIM_BLOCKS = False
LSTRIP_BLOCKS = False
NEWLINE_SEQUENCE = "\n"
KEEP_TRAILING_NEWLINE = False

# default filters, tests and namespace

DEFAULT_NAMESPACE = {
    "range": range_type,
    "dict": dict,
    "lipsum": generate_lorem_ipsum,
    "cycler": Cycler,
    "joiner": Joiner,
    "namespace": Namespace,
}

# default policies
DEFAULT_POLICIES = {
    "compiler.ascii_str": True,
    "urlize.rel": "noopener",
    "urlize.target": None,
    "truncate.leeway": 5,
    "json.dumps_function": None,
    "json.dumps_kwargs": {"sort_keys": True},
    "ext.i18n.trimmed": False,
}
`

SOME Notes:-

- `defaults.py` is located in `lib/jinja2`, 
- lib folder will be generated during the installation process
- this is a temporary solution for this issue

**Comment by CrypticWizard** [comment]
Can anyone please help with this error? What I think is that, the scripts and the app engine are utilizing python2.7 but the packages installed by 'deps' script conforms to the default version while installing modules which is 3.8 in my case, thereby rendering the app engine incapable of recognizing the modules. I may be totally wrong here, Any help is appreciated.

Here's the log:

```bash 
crypticwizard@pop-os:~/Code/chromium-dashboard$ npm start

> start
> npm run build && ./scripts/start_server.sh


> build
> gulp

[17:11:05] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[17:11:06] Using gulpfile ~/Code/chromium-dashboard/gulpfile.babel.js
[17:11:06] Starting 'default'...
[17:11:06] Starting 'clean'...
[17:11:06] Finished 'clean' after 9.55 ms
[17:11:06] Starting 'styles'...
[17:11:06] Finished 'styles' after 497 ms
[17:11:06] Starting 'js'...
[17:11:07] Finished 'js' after 600 ms
[17:11:07] Starting 'lint-fix'...
[17:11:08] Finished 'lint-fix' after 1.22 s
[17:11:08] Starting 'rollup'...
[17:11:15] Finished 'rollup' after 6.96 s
[17:11:15] Finished 'default' after 9.29 s
INFO     2021-03-14 11:41:16,981 devappserver2.py:289] Skipping SDK update check.
INFO     2021-03-14 11:41:17,660 api_server.py:282] Starting API server at: http://localhost:35853
INFO     2021-03-14 11:41:18,045 dispatcher.py:267] Starting module "default" running at: http://localhost:8080
INFO     2021-03-14 11:41:18,371 dispatcher.py:267] Starting module "notifier" running at: http://localhost:8081
INFO     2021-03-14 11:41:18,373 admin_server.py:150] Starting admin server at: http://localhost:8000
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 206, in <module>
    main()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 177, in main
    sandbox.enable_sandbox(config)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 317, in enable_sandbox
    THIRD_PARTY_C_MODULES.get_importable_module_names(config))
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 867, in __init__
    dep_lib = __import__(dep_lib_name)
ImportError: No module named enum
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 206, in <module>
    main()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 177, in main
    sandbox.enable_sandbox(config)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 317, in enable_sandbox
    THIRD_PARTY_C_MODULES.get_importable_module_names(config))
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 867, in __init__
    dep_lib = __import__(dep_lib_name)
ImportError: No module named enum
ERROR    2021-03-14 11:41:21,121 instance.py:284] Cannot connect to the instance on localhost:16646
ERROR    2021-03-14 11:41:21,384 instance.py:284] Cannot connect to the instance on localhost:18443```

**Comment by whoanuragverma** [comment]
Finally, I can run the local development environment without any errors after days of debugging. I found out the following things:

- App Engine throws an error for Enum, Six, and other modules if you don't use the same package manager for installing App Engine SDK as the one which you used for installing Google Cloud SDK. For Example, If you have installed Google Cloud by apt then you should use **apt only for installing the GCloud components** if you directly downloaded from the website then you should only use the **gcloud command to install**.
- Check for pip command, currently, the code runs on Python2. Thus, you should only use pip2 for installing packages from requirements.txt
- I am not sure about `jinja2.tests` however I found out that using a clean system i.e. fresh OS install doesn't throw the Exception. This may be because of conflicting Jinja2 pre-installed in your system. **<ins>Not sure</ins>** about this tbh.

**Comment by jrobbins** [comment]
I have also hit the error with jinja2.tests.  And, I also worked around it by the hack of editing files under lib/jinja2.   I have spend some time looking into it, but It is a mystery to me as to what the root cause of that error is.  So, if anyone can figure it out, that would be a big contribution.

As shivamag00 wrote above, you could include the contents of tests.py in defaults.py.   My solution was to comment out a few lines of defaults.py that reference tests.py.  It turns out that the app does not actually use those comparison operators in our templates.

I apologize for this poor initial experience when working with this code.  Eventually, we will get off python2 and upgrade all our libraries.  However, we have too many dependencies on GAE libraries that are only available in python2.  We need to resolve some of the GitHub issues that deal with py2 to py3 upgrades first, then we will be able to make the jump to py3.

**Comment by codereverma** [comment]
Thank you @whoanuragverma @jrobbins @shivamag00. I can now run the local development environment. I am closing this issue now.

**Comment by jrobbins** [comment]
FYI, I added a note about this to the README.md file.  And, I am tracking the root cause in #1204.

**Comment by jrobbins** [comment]
After some recent changes on my local system, I also started getting the error message about not being able to import enum.  And, then an error about not being able to import protobuf.

I resolved it by running:
python -m pip install grpcio
python -m pip install protobuf

I will add a note about those commands to the README.md file.

**Comment by codereverma** [comment]
Frankly speaking the codebase seems to be very outdated and a lot of stuff
seems to be "hacked" up to make it work. For example installing python
dependencies from npm seems bit weird to me.

If I had an opportunity to rewrite this code I'll be probably using
next.js/gatsby for the frontend because they super fast and super scalable.
For the backend firebase or graphql would be really amazing.
