### ISSUE TITLE
Proposed, In development, and Deprecated features are not showing on mobile view.

### ISSUE THREAD

**Issue by khubaibalam2000** [GoogleChrome/chromium-dashboard#1242]
**Describe the bug**
On desktop, there is a side panel in which proposed, in development, deprecated features, and milestones can be seen. But this functionality is not showing on the mobile. The attached screenshot is of the desktop view of site, in mobile view, one cannot see this side panel.

![image](https://user-images.githubusercontent.com/74249716/112805058-8d946300-908e-11eb-9dbd-d1e387e657ce.png)

**To Reproduce**
On mobile
1. Go to https://chromestatus.com/features
2. Try to find the filter of 
    a. Proposed 
    b. In development 
    c. Deprecated
    d. Milestones

**Expected behavior**
I think there should be a filter for the proposed, in development, and deprecated features. Also there should be a milestone page or functionality.

**Comment by shubhammittal588** [comment]
@media only screen and (max-width: 700px)
#drawer-column {
    display: none;
}
the display with (max-width:700) is set to none that's why it disappear in mobile mode. We can create a dropdown taking the id="drawer-column" setting min-width=699px
![Screenshot 2021-04-03 at 4 59 13 PM](https://user-images.githubusercontent.com/77587202/113477286-6c70af80-949e-11eb-8922-1d975dee27ba.png)

**Comment by shubhammittal588** [comment]
correction:
max-width:700px with display: block; in a dropdown
