### ISSUE TITLE
Flask in Django

### ISSUE THREAD

**Issue by shivamag00** [GoogleChrome/chromium-dashboard#1270]
This may be very naive... The developer documentation says that the backend is Django. However, on browsing the code, one would realise that flask is also being used. This makes me think that Flask is being used in Django. Since, Flask is viewed as an alternative to Django, I just want to confirm - is Flask being used in Django here ?

@jrobbins

**Comment by jrobbins** [comment]
We use Django just for HTML templates and forms (see FlaskHandle.render() and guideforms.py).   The app used to use a combination of Django plus webapp2, now it uses Django plus Flask.  Flask is being used for all the request handlers (see basehandlers.py and all the code under api/ and pages/).

We don't have a huge amount of HTML templates, in part because we use webcomponents to generate a lot of the page contents (see static/elements).

Going forward, I would like to step closer to having less done through Django templates and more being done through web components plus JSON API handlers.  However, there's no deadline for that and nothing else depends on that being done.  New things added to the app should be done with web components and APIs as much as possible.

**Comment by jrobbins** [comment]
And, one reason to continue with Django forms, at least for a while, is that we are frequently adding new DB fields to the Feature object and new UI form fields to guideforms.py.  Django makes it very easy to define forms that have one field per row.  It means that we can do that without editing HTML, and we can even have unit tests for the python code that builds those forms.  For example, we have a python unit test to check that any form field added to the editing UI is also included somewhere on the detail display page.

**Comment by jrobbins** [comment]
Two big weaknesses of our use of webcomponents are:

1. We lack JS unit tests.  We could set up JS unit tests using jasmine and karma or some other JS libraries and tools.  We would need to use npx to run a browser to run the JS tests from the commandline.  Then, we could add that to Travis-CI (or whatever CI tool we might use instead.)

2. The data in our webcomponents follows no particular pattern for updates and there is no pattern to the way that the components fetch data from the server.   It would be good to design that in a consistent way.  For example, following the React approach of passing a unified state object down from the top level and firing events to make changes, regardless of whether or not we end up using the react JS library.

**Comment by shivamag00** [comment]
Thank You @jrobbins ... This really helps.

**Comment by jrobbins** [comment]
Closing this issue because I think that I answered your question.

I'll also note that it might be nice to phase out our use of Django and instead use Jinja2 templates.  However, we would need a convenient way to manage form generation.  That change is not as important as other things that we could be working on, like all aspects of the python3 upgrade.

**Comment by shivamag00** [comment]
I will update the developer documentation with this info so that it could help new contributors in the future.

**Comment by shivamag00** [comment]
FIY, I modified the developer docs with the above info.
