### ISSUE TITLE
Process: Clearly define the roles and responsibilities for API OWNERS

### ISSUE THREAD

**Issue by cwilso** [GoogleChrome/chromium-dashboard#1329]
Clearly define the roles and responsibilities for API OWNERS, and link that into the Launching features page, as well as the FAQs. Use consistent language about what the API Owners ARE.

**Comment by cwilso** [comment]
All of the Frequently asked questions on the Launching features page currently reference the role of API Owners in some form. We mention a few times what API Owners are NOT, like “They are not necessarily leads or overseers of any of the code.” and “ they are not gatekeepers for everything”. However, I can’t find any definition of what they ARE, or the clearly defined roles and responsibilities of API Owners.

The Web Platform Values doc has a section for “The role of the API OWNERS” where the statement is “they are the final approvers in the Blink process”. This is somewhat contradictory to the language used in the FAQs above.

**Comment by jyasskin** [comment]
https://crbug.com is probably a better place for this sort of issue, since it's about https://source.chromium.org/chromium/chromium/src/+/main:docs/website/site/blink/launching-features/index.md instead of code in this repository. I think this issue is also fixed: https://www.chromium.org/blink/guidelines/api-owners/ says "The Blink API owners oversee, enforce and evolve the [Blink Intent process](https://www.chromium.org/blink/launching-features). Their most public role is to approve experimentation and shipping of new or changed [web-exposed](https://www.chromium.org/blink/guidelines/web-exposed) [APIs](https://chromestatus.com/features) to Chromium-based browsers."
