### ISSUE TITLE
Border-radius use counter stat shows >100% of page loads

### ISSUE THREAD

**Issue by juwain** [GoogleChrome/chromium-dashboard#1374]
There is probably an issue with data of the border-radius property [rank usage metrics](https://chromestatus.com/metrics/css/popularity). In the middle of the 2018 stats shows 109% of page loads. 

![55005FCF-F6C3-40DC-89C2-DDEB6A04FBC9](https://user-images.githubusercontent.com/928081/123513252-cdbab000-d694-11eb-98d3-db2890889cdf.jpeg)

1. Go to https://chromestatus.com/metrics/css/timeline/popularity/53.
2. See error in chart. 

![E5967E96-A4B4-4052-AA9B-8C1FC644774D](https://user-images.githubusercontent.com/928081/123513646-d01e0980-d696-11eb-9009-a548e8730376.png)

Expected behavior: percent of page loads should not to be more than 100%.

**Comment by jrobbins** [comment]
The fix was deployed.

The underlying cause was:
+ There was a datapoint for border-radius that had a value of 109% back in 2018 or so.  I don't know the story behind that.
+ We were failing to sort datapoint by date when generating this page, so old datapoints were sometimes shown.
+ We recently upgraded our datastore library, so default sorting may have changed, resulting in a more noticeable incorrect value being surfaced.
