### ISSUE TITLE
Metrics stalled since 2021-11-03.

### ISSUE THREAD

**Issue by mikewest** [GoogleChrome/chromium-dashboard#1602]
The metrics reported via endpoints like https://chromestatus.com/data/timeline/featurepopularity?bucket_id=1692 has stalled; I've spot-checked a few, and I don't think there have been updates generally since 2021-11-03.

**Comment by jrobbins** [comment]
It looks like our GAE instances were running out of RAM while fetching metrics data. 

I was able to resolve it without a code or configuration change by just hitting `/cron/metrics?date=...` a few times with specific dates.

I think the easiest way to prevent this from happening again would be to increase the RAM for each instance.  

And, we need to add monitoring.  These errors did not show up on the cloud console Error Reporting page, maybe because the request never produced a response.

**Comment by mikewest** [comment]
https://chromestatus.com/data/timeline/featurepopularity?bucket_id=1692 has stalled out since the 13th and is missing some days prior to that. It looks like other metrics are having similar issues (https://chromestatus.com/data/timeline/featurepopularity?bucket_id=3199 for example). Is it possible that there's still an issue with the metrics pipeline?

**Comment by jrobbins** [comment]
Yeah, this looks like a new problem.  We are getting an error response from uma-export.  I will reach out to that team.

**Comment by jrobbins** [comment]
A performance improvement in uma-export is in review now.

**Comment by mikewest** [comment]
Spot-checking metrics, it looks like the change you made fixed things, and then it died again sometime after the 21st. :/

**Comment by jrobbins** [comment]
Thanks.  I'll look into it today.

**Comment by jrobbins** [comment]
I cleared our capstone records (which indicate that metrics data for a given day were completely saved) and then hit `/cron/metrics` and it saved some data.

I'm having a hard time pinning it down because the GAs cloud debugger is not working.    However, my current theory is that the new version of uma-export sends a response that has an 'r' field with an empty list value in the case when the metrics data is not ready.  The old version simply did not include an 'r' field.  My code uses the presence of the 'r' field as an indication that data was ready.

That bug would result in the missing data points and would be consistent with my ability to backfill the data as I have done.

Tomorrow, I'll deploy a version of the app that has additional logging statements so that I can verify the theory.  I'll check with chrome-metrics-team that the change in behavior is expected.  I can simply treat `'r': []` as a day when data is not ready yet.  I just want to make sure that the uma-metrics app never gives me half-complete data.

**Comment by jrobbins** [comment]
This was resolved back in December by #1630.
