### ISSUE TITLE
Unable to comment on an approved item in "My Features"

### ISSUE THREAD

**Issue by dbratell** [GoogleChrome/chromium-dashboard#1644]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

In the "My Features" section I approved an item, and after that I was unable to save a log update. This may be related to Item #1641 where I was unable to change the status. Maybe both happened for the same reason. Or maybe not.

**To Reproduce**
I've only one item set to approved and I do not want to "approve" anything just to test so I will go from memory here.

I performed the following steps. many of them are probably unnecessary.

1. Opened an item by clicking the stamp icon.
2. Set the dropdown to approved.
3. Clicked the save button, though nothing seemed to happen.
4. Wrote a few words in case the save button needed that to work. 
5. Clicked the save button. Nothing seemed to happen.
6. Closed the item.
7. Opened the item by clicking the stamp icon.
8. Noticed that the item was set to approved but the comment was not in the log.

**Expected behavior**
The text I wrote should have been in the log.

**Comment by jrobbins** [comment]
In the logs I see a bunch of 403 responses at around this time from a user using Opera 81.0.4196.27.   So, I think the underlying cause of this problem is probably that your Google Sign-In session expired.   That is our probably mistake rather than anything that you did.  

Our Google Sign-In sessions seem to last one hour, which is too short to do real work.  We need to figure out how to configure it to be longer and/or refresh the session as needed.  This might also be the right time for us to upgrade to Google Identity Services since Google Sign-In is deprecated.

Also, we don't show user-visible error messages when XHR requests fail.  I need to add that.

**Comment by jrobbins** [comment]
A (poor) work-around for now is to sign out and sign back in if you notice things not working.

**Comment by dbratell** [comment]
Closing this since it was just a symptom of issue 1649.
