### ISSUE TITLE
Two feature IDs have the same name

### ISSUE THREAD

**Issue by sbingler** [GoogleChrome/chromium-dashboard#1692]
**Describe the bug**
https://chromestatus.com/metrics/feature/timeline/popularity/3962 and https://chromestatus.com/metrics/feature/timeline/popularity/3965 each have the title "TapDelayEnabled" even though they're different IDs with different data.

**To Reproduce**
1. Visit [3962](https://chromestatus.com/metrics/feature/timeline/popularity/3962) and [3965](https://chromestatus.com/metrics/feature/timeline/popularity/3965)
2. Notice the same title yet different data and IDs.

**Expected behavior**
Based on the [web_feature](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/web_feature/web_feature.mojom;l=3279;drc=faca05cd89092831581e3ab2e6b6787db34bf34a) file I expect that 3962 has the title "SameSiteCookieInclusionChangedByCrossSiteRedirect" and 3965 has "TapDelayEnabled"

**Comment by jstenback** [comment]
This is rather peculiar, thanks for filing this bug! Per a quick initial investigation it seems like https://chromestatus.com/metrics/feature/timeline/popularity/3965 shows the actual data for the TapDelayEnabled use counter, as that ID maps to the right use counter AFAICT (https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/blink/public/mojom/web_feature/web_feature.mojom-lite-for-compile.js;drc=926a6cb753ee3d4b427d033c71cfc8e3af400842;l=3176), but https://chromestatus.com/metrics/feature/timeline/popularity/3962 does not, that seems it ought to map to the SameSiteCookieInclusionChangedByCrossSiteRedirect per https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/blink/public/mojom/web_feature/web_feature.mojom-lite-for-compile.js;drc=926a6cb753ee3d4b427d033c71cfc8e3af400842;l=3173.

@jrobbins can you check if this inconsistency appears in the raw data that we get from the metrics end point, or if this is something that chromestatus.com gets confused about internally?

**Comment by jrobbins** [comment]
Our datastore has two FeatureObserverHistorgram entries with bucket_id = 3962.  I will delete the wrong one, but first I am looking into where that bad entry may have come from and if there are any others like it.

**Comment by jrobbins** [comment]
Chromestatus gets the names of the metrics from enums.xml.

On June 20, 2021, a CL was landed with
<int value="3962" label="TapDelayEnabled"/>
https://chromium.googlesource.com/chromium/src/+/d49bc9b76c55fe41849c0e7ac0437957b1ddda01%5E%21/#F9
I think that happened around midnight in the pacific timezone.

At 4am pacific, our cron job fetched and parsed that file an added an entry for TapDelayEnabled with bucket_id 3962.

That change was reverted 5 hours later in
https://chromium.googlesource.com/chromium/src/+/b0d2c7f682969e65755ed6a4a6fb2debe0395b83
But, chromestatus does not remove FeatureObserverHistorgram entries that already exist.


Since 3962 seemed to be available in the file, the next time someone wanted to add one, they used that bucket_id.
<int value="3962" label="SameSiteCookieInclusionChangedByCrossSiteRedirect"/>
https://chromium.googlesource.com/chromium/src/+/2db3a4287cc5ebbd7b1189509380cfc5647715ef


Then the original change was remanded on July 26, 2021 with
<int value="3965" label="TapDelayEnabled"/>
https://chromium.googlesource.com/chromium/src/+/fcfc3f925a444baf122592cbf1f69a724dc3c86d%5E%21/#F9

So that explains the double entries for TapDelayEnabled.  I think that I can safely delete the old bucket_id for TapDelayEnabled.

As for how to avoid this problem in the future: it might make sense to treat the bucket_id like a unique key (that is, delete any prior entries with that same bucket_id when writing a new one).

**Comment by jrobbins** [comment]
I deleted the duplicate entry.   Now, the URLs in the issue description now show distinct title.  So, I believe that the immediate problem is resolved.

I'm tracking the work to prevent a similar problem in the future in issue #1693.

**Comment by sbingler** [comment]
Thanks for the quick resolution!

Was this just a naming mix up? Is the data being displayed for [3962](https://chromestatus.com/metrics/feature/timeline/popularity/3962) coming from the correct source?

**Comment by jrobbins** [comment]
> Was this just a naming mix up? Is the data being displayed for [3962](https://chromestatus.com/metrics/feature/timeline/popularity/3962) coming from the correct source?

Yes, I think so.  We don't use the histogram bucket_id to look up metric values.  We just ask uma-export to give us all metrics.  So, unless umm-export had the same problem, the metrics we get from there should be correct.
