### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by cosmicwanderer7** [GoogleChrome/chromium-dashboard#1813]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
Whenever I try to run npm start it returns  Failed to connect to localhost port 15606: Connection refused

> start
> source cs-env/bin/activate; (npm run start-emulator-persist > /dev/null 2>&1 &); sleep 6; curl --retry 4 http://localhost:15606/ --retry-connrefused; npm run start-app; status=$?; npm run stop-emulator; exit $status
sh: 1: source: not found
curl: (7) Failed to connect to localhost port 15606: Connection refused
Warning: Transient problem: connection refused Will retry in 1 seconds. 4 
Warning: retries left.

![image](https://user-images.githubusercontent.com/65147258/161208490-a66887e5-53ef-40ca-8408-c1cba74fbf85.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Go to chromium-dashboard folder in your directory.
2. Start the server by `npm start`
3. It says curl: (7) Failed to connect to localhost port 15606: Connection refused
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behaviour**
To start the main server and the notifier backend.

**Additional context**
I tried to change the port by editing testing_config.py but it won't make any changes.
Tried to run `npm start` after disabling firewall returns same results

**System info**
OS: Linux Mint 20.3 x86_64
DE: Cinnamon 
Shell: bash 5.0.17 
Terminal: gnome-terminal

**Comment by amuuth** [comment]
I am getting this error as well.

**Comment by cosmicwanderer7** [comment]
@amuuth Which operating system are you using?

**Comment by jrobbins** [comment]
It looks like the `source` command is failing.   The fact that it fails prevents the datastore emulator from being started, and since the datastore emulator is not running, the `curl` check to see if it is running fails.

(1) `source` is just a bash built-in.  I see that a `source` command succeeded for you before you ran `npm` so it can work for you at the prompt.  However, maybe your system is running the `sh` or `csh` shell for npm  scripts.  You could try editing package.json to replace the `source` command with the `sh` notation which uses just a dot `.` to indicate that a shell file should be loaded.

(2) Alternatively, you could simply delete the `source cs-env/bin/activate;` part of that npm script.  It is there as a convenience so that we do not need to to the `activate` each time we sign in.  If you do the `activate` command yourself, then it does not need to be in the npm script. 

Trying one of (1) or (2) should help you progress further.

For the gulp errors, I thought that those would be installed by the `npm ci` command on step 3 of README.md.  Try doing `npm ci` again and check for errors.

**Comment by cosmicwanderer7** [comment]
gulp errors got resolved after I manually installed all the dependencies.

**Comment by jrobbins** [comment]
It sounds like you made it passed these problems.  If not, comment here and I can reopen this issue.

**Comment by impact-maker** [comment]
Hi, jrobbins followed all the steps on readme file but still encountering same error. Attaching the screenshot below

![Screenshot from 2024-01-05 09-05-28](https://github.com/GoogleChrome/chromium-dashboard/assets/86894399/1b214d97-9f9a-479b-bc74-c33f0810fe62)
![Screenshot from 2024-01-05 09-05-36](https://github.com/GoogleChrome/chromium-dashboard/assets/86894399/79e4846e-9139-4408-a9e7-2574ca097e77)
![Screenshot from 2024-01-05 09-05-28](https://github.com/GoogleChrome/chromium-dashboard/assets/86894399/f1c5a029-28c4-4b04-887c-ca4d2f272f26)
![Screenshot from 2024-01-05 09-05-36](https://github.com/GoogleChrome/chromium-dashboard/assets/86894399/013c5d47-8ecb-4657-8c6b-639700203750)
