### ISSUE TITLE
The use counter <select> menu doesn't show a value above feature #4080

### ISSUE THREAD

**Issue by mfreed7** [GoogleChrome/chromium-dashboard#1814]
**Describe the bug**
The `<select>` box that contains all of the feature descriptions stops displaying anything above feature #4080.

Example:
- https://chromestatus.com/metrics/feature/timeline/popularity/4077 - shows "FileSystemUrlNavigation"
- https://chromestatus.com/metrics/feature/timeline/popularity/4078 - shows "V8Navigator_AdAuctionComponents_Method"
- https://chromestatus.com/metrics/feature/timeline/popularity/4079 - shows "ClientHintsUAFullVersionList"
- https://chromestatus.com/metrics/feature/timeline/popularity/4080 - **blank** description
- https://chromestatus.com/metrics/feature/timeline/popularity/4081 - **blank** description
- https://chromestatus.com/metrics/feature/timeline/popularity/4082 - **blank** description

**To Reproduce**
1. Visit URLs above.

**Expected behavior**
The descriptions work for all features, not just old ones.

**Additional context**
If this turns out to be a bug in the `<select>` menu itself, please report it to crbug.com/new and CC masonf@chromium.org. However, I don't believe it is, since I inspected the page and I don't even see `<option>` elements added to the DOM for anything above 4080. So I'm guessing this is a backend or site issue.

**Comment by andruud** [comment]
I noticed that the feature name of `4082` is `Feature_4082` instead of the expected `CSSMediaListUnknown`.

![image](https://user-images.githubusercontent.com/77163/163031235-6a623ab0-0dc3-4b5f-99b4-f64a70980a37.png)

If I query some older ID, e.g. `279`, then the feature name is `SVGClassName`, and not (for example) `Feature_279`. Maybe the bug is related to the feature name being messed up sometimes. Though maybe not _only_ that, since `4079` has the name `Feature_4079` in HA, yet somehow chromestatus has the real name for that one.

**Comment by past** [comment]
Sounds like we need another update like https://github.com/WPO-Foundation/wptagent/pull/468. Filed https://github.com/WPO-Foundation/wptagent/issues/494

**Comment by past** [comment]
Filed https://github.com/GoogleChrome/chromium-dashboard/issues/1838 for a better long-term fix.

**Comment by jrobbins** [comment]
We populate that `<select>` by fetching data from
`https://chromium.googlesource.com/chromium/src/+/master/tools/metrics/histograms/enums.xml?format=TEXT`
The file is too big to view in gitilies, so that URL downloads it and you can decode it with a command line like
`base64 --decode enums.xml.txt > enums.xml`

In that file, I see lines 31,115 to
`
enum name="FeatureObserver">


  <int value="0" label="OBSOLETE_PageDestruction"/>
  <int value="1" label="LegacyNotifications"/>
...
  <int value="4077" label="FileSystemUrlNavigation"/>
  <int value="4078" label="V8Navigator_AdAuctionComponents_Method"/>
  <int value="4079" label="ClientHintsUAFullVersionList"/>
</enum>
`

So, I think we need to get that file updated.  The comment on that `<enum>` says that it is generated by a python script, but I don't know how that normally gets run or how to run it manually yet.

**Comment by jrobbins** [comment]
I checked out the chromium source code to see the current state of enums.xml.   I see that there are actually more FeatureObserver values that I was getting through gitiles.  So, I am thinking that this is a gitiles bug, or the file it is serving is at least stale.  In the latest version of enums.xml those features go up to value="4211".

**Comment by jrobbins** [comment]
OK, the problem is that we have been fetching from this URL for years:
`https://chromium.googlesource.com/chromium/src/+/master/tools/metrics/histograms/enums.xml?format=TEXT`
however, at some point the name of the branch was changed from master to main.  So, we should be fetching from
`https://chromium.googlesource.com/chromium/src/+/main/tools/metrics/histograms/enums.xml?format=TEXT`
or something similar.

I make a simple PR to use the new URL.

**Comment by jrobbins** [comment]
OK, that seems to be the problem.  After deploying my draft PR to staging and running our cron job, I am able to view metrics higher than 4080.  E.g., https://cr-status-staging.appspot.com/metrics/feature/timeline/popularity/4188

**Comment by jrobbins** [comment]
The fix went live yesterday and seems to have worked.
