### ISSUE TITLE
google chrome feature request

### ISSUE THREAD

**Issue by FrancoFrancis** [GoogleChrome/chromium-dashboard#1946]
I am a web developer I get really pissed when I end up with too many open **tabs** in my browser.

It would be amazing to be able to mark several open **tabs** and close them at once, instead of having to click and close tabs one at a time.

**Comment by jrobbins** [comment]
Thanks for raising this issue.  In this case there is good news because it turns out that you can already do that.  Just shift click on the tabs, then pop up a menu on one of them and choose "Close".

Having said that, I am going to close this issue.  Not because of the existing browser functionality to do that, but because this is the wrong issue tracker for browser feature requests.  This issue tracker is only for the chromestatus.com website.  To report problems or request features for the chrome browser itself, please use https://bugs.chromium.org/p/chromium, or use the "Help" > "Report an Issue" menu item in the Chrome application.
