### ISSUE TITLE
Media Source Extensions for WebCodecs Demo links to Editor's Draft

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chromium-dashboard#2009]
**Describe the bug**
Media Source Extensions for WebCodecs Demo links to Editor's Draft

**To Reproduce**
1. Go to [Feature: Media Source Extensions for WebCodecs](https://chromestatus.com/feature/5649291471224832)
2. Click on link beneath "Demo"
3. The link navigates to Media Source Extensions Editor's Draft, not a demo 

**Expected behavior**
Directed to an demo.

**Additional context**

**Comment by jpmedley** [comment]
Sorry for not getting back to you sooner. The problem here is that Demo field is labeled 'Samples' for people who are filling out the form. That needs to be fixed and I don't have a resolution for that yet.

Thank you for the demo. I'll pass it on to the feature owner, but he may or may not add it. It depends on how well it matches the intent of the feature's design, among other things.

**Comment by guest271314** [comment]
I filed this for the missing link.

Do or not do what you want with the demo. I posted my observances re MSE for WebCodecs here https://groups.google.com/a/chromium.org/g/blink-reviews/c/HOvZrUcYg-I/m/FbpVjX86AQAJ.

**Comment by jpmedley** [comment]
Thanks.
Joe Medley | Technical Writer, Chrome DevRel | ***@***.*** |
 816-678-7195
*If an API's not documented it doesn't exist.*
