### ISSUE TITLE
Feature creation and editing allows form submission with invalid text fields

### ISSUE THREAD

**Issue by DanielRyanSmith** [GoogleChrome/chromium-dashboard#2014]
**Describe the bug**
When creating a new feature or editing an existing one, submitting the form via the `Submit` button will allow form submission even when required text fields are empty or invalid.

**To Reproduce**
1. Open the form to create a new feature using the `Add new feature` button on the features tab.
2. Select one of the radio buttons for `Feature type` (this field is required and validation works as expected).
3. Click `Submit`. The field should briefly display error messages regarding the unfinished required text fields, but then the request will process, the feature will be created, and the user will be redirected.

**Expected behavior**
Submission should be blocked until all required fields have valid input.

**Comment by jrobbins** [comment]
One potential solution would be to disable the submit button.  We could make a JS listener for change events on all the fields in the form, and run a function to check if any field indicates that it is invalid or not.  If any is invalid, disable the submit button, otherwise enable it.

**Comment by dlaliberte** [comment]
As an experiment, I commented out the contents of addFormSubmitListner and all of upateFormToken (in cs-client.js), and then the form submit button does not submit the form with invalid data, specifically missing Summary text.  Uncommenting again, and then the form does submit.  So this code appears to be the source of the problem, at least when used along with shoelace form fields.  

I note that on https://shoelace.style/getting-started/form-controls it says "If you're also attaching an event listener to the form, you must attach it after Shoelace form controls are connected to the DOM, otherwise your logic will run before Shoelace has a chance to inject form data and validate form controls."  This sounds relevant, though it is not exactly clear why, or how to wait until after Shoelace form controls are connected to the DOM.
