### ISSUE TITLE
Finer grain changes to milestone features

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/chromium-dashboard#218]
In some cases, there are small additions/removals to a feature that dont merrit a new entry but should be documented. A new API added to SW for example. We've been telling people to log these changes in the comments section, but there's no good way to search over that data and now when the change was made. The current timeline orders things by shipped milestone.

One proposal is:
changed in x milestone", and support multiple entries, example:

M46: now it returns a promise
M47: now it doesn't always bypass the http cache
M48: now it does xxx....

cc @ebidel @jeffposnick 

From Paul:
It would be very useful on the slack channel and in other places if the body of the feed items included a summary of the change information.  For example, removals and deprecations would be useful likewise information that says it has just come out from behind a flag.

**Comment by PaulKinlan** [comment]
As can be seen by this example ![screenshot 2015-07-09 at 09 27 34 - edited](https://cloud.githubusercontent.com/assets/45510/8590950/d5108a0c-261c-11e5-8bf5-af8344f5ef52.png)

**Comment by ebidel** [comment]
Trying to think how we could do this without saving a `lastValue` history bit for all important changes...

**Comment by RByers** [comment]
I think we've shifted to filing new status entries, even for minor additions/changes (that land in a different milestone) right?  Otherwise it's just too hard to know what's new when.

Assuming we agree that's the right approach, should we close this bug?  Or maybe what we need instead is some linking between features (being able to mark one feature as a minor change to another one, and then a way to filter by only the major ones and drill down into their dependencies from there).

**Comment by ebidel** [comment]
Yes and no. There are still places people are filling in the details in comments. I think for newer additions/removals, folks are creating new entires.

It would be cool to have "subcards", where changes to a primary feature or sub features get listed under the overall card. Having proper linkage between a set of feature would also be nice. That might get a little tricky with the current visual treatment though. Everything is chronological based on chrome version. If you mix and match, that won't make sense anymore....but maybe it's time to get away from the chrome version as the sorting and just have a feature list?

**Comment by ebidel** [comment]
"If we really do want to keep track of more than the latest status, maybe we could "simply" store shipping, deprecation and removal separately? I think that at least knowing when something was deprecated could be useful, as it would signal to web developers that it wasn't a sudden removal."

**Comment by jpmedley** [comment]
I can think of three use cases. They may be obvious, but if your brain works like mine you'll only be able to think of two of them when you're building. And there may be others I've overlooked.

* Evolving features. This includes both Pau's original use case and something like service worker that gets its functionality over successive releases.
* Deprecate > Remove.
* Behind a flag > On by default

I think the last is where the status quo fails the worst. I have to choose between telling developers they can play with it now or they can roll it out next month. To select the later is to make flagged features harder to find.

**Comment by jpmedley** [comment]
Requires a design process with a PRD and design documents. Adding it to the backlog, because we can't do it now.

**Comment by jrobbins** [comment]
Closing this as done.
I believe that the intent of this issue is being addressed by strategic changes to the scope of the chromestatus site.  Now chromestatus.com focuses on the feature launch process, with each feature launch being separate, but potentially using multiple stages.  While on the other hand, webstatus.dev tracks courser-grained "web features" that grow over time as changes to them are launched.  We do need to do more to link the two sites together, which we are tracking in #4479.
