### ISSUE TITLE
Make Feature owner/editor/CC field mutually exclusive

### ISSUE THREAD

**Issue by DanielRyanSmith** [GoogleChrome/chromium-dashboard#2265]
Currently, it is possible to provide the same email in the owner field, editor field, and CC field. It does not change much to the user experience, but the user will receive additional emails for feature notifications in each field they are listed. It would be useful to have validation to check if a user is listed in 1 field, a warning will display that an email address should only exist in 1 of these 3 fields.

**Comment by jrobbins** [comment]
I think we already avoid sending multiple emails to a single address.   In notify.py we use `accumulate_reasons()` which builds up more reasons to send to each address rather than adding the address itself multiple times.

I can see that in some cases it might be useful to point out that an address is listed multiple times in different fields, but if the downside is minimal, it might be better to not interrupt the user.  Or put another way, it might be better to save our limited number of tolerable interruptions something that has more downside.

**Comment by DanielRyanSmith** [comment]
Perhaps we can close this then if we are careful not to double-notify any users. Probably best to avoid reprimanding users for adding the same email for the reasons you mentioned above @jrobbins 😆
