### ISSUE TITLE
Support fragment links directly to sections within a feature's page

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#2584]
**Is your feature request related to a problem? Please describe.**

https://chromestatus.com/feature/6577673212002304#status links to the top of the feature's page instead of scrolling to the "Status in Chromium" section. This happens because that section is a couple layers deep in shadow DOM, and element `id`s are scoped to their nearest shadow boundary.

**Describe the solution you'd like**

https://github.com/lit/lit/discussions/3524 asks the Lit community if there are any best practices for making this work.

**Comment by jyasskin** [comment]
cc @dlaliberte

**Comment by dlaliberte** [comment]
This failure to scroll to the correct section was only relevant for the editall-page (since it was already working on other pages), and that problem was just fixed by #2789.

However, a few more more link-related issues came to light, which we can track as part of this issue, since it is not really resolved until they are all resolved.

- Any changes in the form fields will be lost without warning by following any links in the help text, whether they go to other form fields or off page. 
- We can handle the 'beforeunload' event, check for any changes in the page, and warn the user if they would lose changes.  Auto-saving is probably too difficult to support with the current architecture.
- We can prevent off-page links from losing the current page form fields by adding target="_blank" to all such links.  Manually maintaining this will not be too onerous though mistakes could be made.
- Links within the page shouldn't be reloading the page at all, but merely scroll to the correct position.  Maybe we need to handle that by replacing such links with href="javascript:..." or 'click' event handlers.  But any such link may or may not go to the same page, depending on how it was composed, so we would have to lookup the link target to see if it is in the page and redirect to a new page if not.

**Comment by dlaliberte** [comment]
#2804 reliably scrolls to hash (fragment) links in the same page without refresh, and also on first draw of the page.  It also fixes several other links off-page to add target="_blank".  

There are still user interactions that result in the user losing unsaved changes, but that turns out to be a bigger problem than correctly handling links, so we can leave that for another PR.
