### ISSUE TITLE
Can we show Opera "In development"?

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#263]
At https://www.chromestatus.com/features/5264933985976320, Opera shows as "shipped", even though they're only going to ship to their dev channel in 37. The 'edit' page only gives me one field for Opera, for all of "enabled by default, experimental, or deprecated".

@perja12

**Comment by ebidel** [comment]
IIRC we basically map all opera_shipped_version to chrome_shipped_version - 13. This might be a good candidate to note in the comments.

https://github.com/GoogleChrome/chromium-dashboard/blob/6b267c054dbddbcae740b504a2f6d182995f86c7/static/js/admin/feature_form.js#L45

**Comment by mathiasbynens** [comment]
It would be nice to have a separate status field for Opera. It could mirror Chrome `X`’s status for Opera `X - 13` as a reasonable default (since they’re both based on the same Chromium version), but then we could manually override it in cases where the status differs. A field like this one:

![](https://cloud.githubusercontent.com/assets/81942/12975465/40d95f44-d0bc-11e5-8807-f2fe6036df41.png)

**Comment by ebidel** [comment]
@mathiasbynens any interest in PRing? :)

**Comment by ebidel** [comment]
@mathiasbynens how often does this come up? I'm weary of adding more fields for owners to fill out / maintain. They already don't do a good job of adding all the data.

**Comment by jyasskin** [comment]
If it has the default that @mathiasbynens suggested, owners don't need to fill it out unless it matters.

**Comment by mathiasbynens** [comment]
@ebidel It’s not that uncommon — it usually happens for one or two features in each stable release. As @jyasskin pointed out, there would be no additional maintenance burden. In the worst case, the owner doesn’t fill out anything special for Opera, in which case the status for Opera would be incorrect — that’s already the case on the current site. The additional field would enable me/others to fix that entry.

**Comment by RByers** [comment]
Per [this thread](https://github.com/GoogleChrome/chromium-dashboard/issues/267#issuecomment-231841554) it would be nice if we could treat Opera deskop and Opera mobile similarly to Chrome on WebView, Chrome Android etc.  I.e. the overall status describes the plan of the blink/chromium project (which reflects the consensus of all the browser vendors built on it via the launch process).   By default that should apply to each shipping product based on chromium/blink, but can be overridden for the unusual case that a blink feature isn't shipped on all browsers.

So I think here we're talking about a feature that has shipped in some chromium product, but hasn't yet shipped in others (either because there are no plans to or because it's blocked), right?  Today I think we do this by leaving the appropriate "shipped in" field blank (eg. how [Push](https://www.chromestatus.com/feature/5416033485586432) is shipped on desktop/android but not webview).  Is that good enough for Opera too?  Of course we should encourage details for special cases to be put into comments.

**Comment by jpmedley** [comment]
#586 Makes this issue moot.
