### ISSUE TITLE
Import status from www.webkit.org/status.html?

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#288]
Splitting off [the discussion](https://github.com/GoogleChrome/chromium-dashboard/issues/114#issuecomment-100457269) of Safari/WebKit.

Perhaps we should just stop trying to talk about signals from Safari (since really those are non-existent until they ship) and instead talk about signals from WebKit?  Then it would make sense to import the data from webkit.org.  Or perhaps we should track both WebKit (for in development) and Safari (for what's actually shipped in a release)?

@BenjaminPoulain any advice?

**Comment by BenjaminPoulain** [comment]
I think Caniuse.com has a nice solution: Instead of listing WebKit, use the name "Safari Technology Preview" and use the purple icon.

Not everything shipping in Safari TP ships in the next Safari, but that gives some idea of what is coming in the future. There is some effort going into disabling unwanted features at runtime in Safari Technology Preview.

If something is missing from the status page, make sure to tell Jon Davis. He can add things that are not being worked on.

**Comment by ebidel** [comment]
+1 for using Safari TP. It didn't exist when we built chromestatus. It has good published notes for each release and follows closing to Safari releases.

**Comment by kevinbarabash** [comment]
Some of the webkit status are wrong.  The WebGL 2 is "No public signals", but https://webkit.org/status/ shows it as "In development".

**Comment by ebidel** [comment]
Thanks. In general, it is difficult for us to keep other vendors's views up to date. If you have any others, let us know.

**Comment by phistuck** [comment]
I suggest that you subscribe to the RSS feed of -
https://platformstatustracker.azurewebsites.net/
Updates across the board, including Chromium.

**Comment by kevinbarabash** [comment]
@ebidel thanks!

**Comment by jyasskin** [comment]
I think we can close this, now that Safari has dedicated positions repository, and https://bit.ly/blink-signals describes how to map it to our states.
