### ISSUE TITLE
CSS usage stat columns do not align with headers on safari or firefox

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#301]
https://www.chromestatus.com/metrics/css/popularity

The columns don't line up with their headers. They do on Chrome.

![image](https://cloud.githubusercontent.com/assets/5472050/16741853/ff875b44-4759-11e6-8947-c46ed78c82a8.png)

**Comment by RByers** [comment]
Looks like this is due to Polymer's ShadowDOM polyfill not being entirely faithful with matching selector specificity.  The rules that apply flex to the `.percent_label` are:
```css
#stack-rank-list li label { flex: 1 }
#stack-rank-list .percent_label  {flex: 2 }
```
Here the `flex: 2` rule has higher specificity (0 vs. 1 class selectors).

But in browsers without true ShadowDOM support it looks like the polyfill is trying to approximate the style encapsulation by adding a class to each element of the selector:
```
.chromedash-metrics-0 #stack-rank-list.chromedash-metrics li.chromedash-metrics label.chromedash-metrics { flex: 1}
.chromedash-metrics-0 #stack-rank-list.chromedash-metrics .percent_label.chromedash-metrics { flex: 2}
```
Here the `flex: 1` rule has higher specificity (4 class and 2 type selectors vs. 4 class and 0 type selectors).

So looks like the only interop bug is differing support for Shadow DOM, and an imperfect polyfill.  I'll rework the rules somehow to avoid this.

**Comment by ebidel** [comment]
The style shimmer is correctly adding the prefix classes for chromedash-metric instances. I think we may just need to have better specificity to account for polyfill vs. native. `!important`ftw!

**Comment by RByers** [comment]
Heh, I think I can clean this up a bit better than just using `!important`.  I'll put up a PR shortly.
