### ISSUE TITLE
Feature popularity timeline view does not resize on small viewports

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#304]
The graph showing feature usage over time doesn't resize when the viewport changes and this leads to horizontal scrolling on narrow viewports

![image](https://cloud.githubusercontent.com/assets/5472050/16742166/5ba7f766-475b-11e6-84de-92fbaefb4b65.png)

**Comment by jpchase** [comment]
Should wait for #311 before tackling this one?

**Comment by ebidel** [comment]
I'm currently working on #311, but this is a bit different. It'll require a `resize` listener + updated calls to the Google Charts API. AFAIK, it doesn't have responsive stuff built in. 

If someone wants to take it that would be great. Might be difficult until we figure out https://github.com/GoogleChrome/chromium-dashboard/issues/318. Good news is that I've made progress on #318! Will post instructions soon.

**Comment by jpmedley** [comment]
@jrobbins This still appears to be true.

**Comment by abhishekrawe** [comment]
i want to work on this issue .

**Comment by Mahboub99** [comment]
I would like to work on this issue .

**Comment by whoanuragverma** [comment]
@jpmedley I can make the chart horizontally scrollable on mobile using CSS because resizing it to fit makes it difficult to interpret what is being presented. However, this page has a lot of other problem on small screens, for example text doesn't wrap around view port width which is also easily accomplishable with CSS only. However, I am having trouble resizing the second chart as it comes from a third party(HTTP Archive). Please tell me how do you want the second chart to be displayed, after fixing this I'll make PR.

**Comment by CrypticWizard** [comment]
@jpmedley  @jrobbins Is there a way I can import the prod db to local dev db for testing to work on this issue? I am not able to do so since data is not available in devserver.  #318 was raised for the same. Also, its listed as TODO for @liyangguang in the `chromedash-timeline.js` file  
> TODO(yangguang): This component is not tested. Data is not available in devserver, so cannot be tested locally.

**Comment by GouravSingal-code** [comment]
can i work on it?

**Comment by jpmedley** [comment]
This appears to be fixed.
