### ISSUE TITLE
Chrome version number obscured by scroll bar on Safari with narrow viewport

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#305]
When the viewport on Safari becomes narrow enough, a permanent scroll bar is shown that blocks out the 1's digit of the version number

![image](https://cloud.githubusercontent.com/assets/5472050/16742317/037817d2-475c-11e6-9ce9-a39b52354373.png)

**Comment by drufball** [comment]
We also show two scrollbars in this case:

![image](https://cloud.githubusercontent.com/assets/5472050/16742360/3bd204b2-475c-11e6-90cd-a50a8498aec9.png)

(hard to get a good screenshot since the smaller scroll bar hides quickly)

**Comment by RByers** [comment]
Ooh, Chrome / Safari scrolling interop issues - my favorite class of problems ;-).  Thanks!

**Comment by RByers** [comment]
The double scrollbars are due to the nested scrolling as discussed in #311.  Sounds like @ebidel is going to eliminate that, so let's block on that.

The issue with the scrollbar overlapping the Chrome version number occurs for me only when moving the mouse over top of the scrollbar so that it grows to be easily draggable.  Really this is a Safari design issue (overlay scrollbars that grow over top of the content) though we could add a bit more right padding to accomodate.  Let's wait and see how things look after #311 and then revisit.

**Comment by clelland** [comment]
It's more of an OSX thing: On a mac, Chrome and Firefox also show the scrollbar over the content:

Firefox:
<img width="154" alt="screen shot 2016-07-14 at 11 55 57 am" src="https://cloud.githubusercontent.com/assets/45853/16846368/2cc4be50-49ba-11e6-9f11-792a0cb48f7a.png">
Chrome:
![screen shot 2016-07-14 at 12 00 43 pm](https://cloud.githubusercontent.com/assets/45853/16846721/89075fb4-49bb-11e6-86d3-b3377ff5202a.png)

**Comment by RByers** [comment]
Yep, and we're trying to add overlay scrollbars to Chrome on other platforms too (scrollbars not affecting layout is really a saner model).  I guess this stuff feels pretty tight - certainly wouldn't hurt to add a bit of padding anyway.

**Comment by jpmedley** [comment]
The headings in question are no longer part of the interface.
