### ISSUE TITLE
Explore removing milestone as the primary way features are listed

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#307]
Need to brainstorm this more, but it's unclear if sorting features chronologically by milestone is the best way to present the list. chromestatus has evolved over time and ultimately, people just want to drill down into features, see the list of features for a given milestone, etc. 

Sorting them by milestone might not make sense anymore.

**Comment by jpmedley** [comment]
I hope you mean as the default.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by ebidel** [comment]
Yes

**Comment by clelland** [comment]
I'll take a look at what I can do in this space; brainstorming ideas are welcome!

**Comment by ebidel** [comment]
Rethinking this a bit for discussion....:

One things about the chronological list is that it's really good for quickly groking what features are in active dev / proposed vs. actually landing. I think anything new may want to preserver that separation. Speculative features are different from launching/ed features. Web devs mostly care about the latter.

Chronological is also useful for seeing "what's new". For example, if the list was alphabetical, you may never see newer features. That seems less useful to me.

**Comment by jpchase** [comment]
I'll agree it seems more useful to group features into categories like speculative, launched/launching, stable, and "what's new". As the list of features continues to grow, it seems less useful to order/scroll the entire list of features by milestone.  Once you're past the upcoming/current/recent milestones, I think it's far more usable to be able to jump directly to an older milestone.

We could keep the list of milestones in the left nav, and add/rework the top of the nav to represent the desired categories ("what's new" and so on).

I would suggest changing the left nav so that clicking on a milestone (or category) would filter the list (a shortcut for typing a milestone filter in the short box). This replaces the behaviour of scrolling to the milestone in a chronological list. That way, users can still answer the question "what's in milestone X", but it allows the list to be sorted/grouped in different ways.

**Comment by ebidel** [comment]
> I would suggest changing the left nav so that clicking on a milestone (or category) would filter the list

Might make sense to make the list a dropdown instead? That way it becomes a filtering control and we can move it near the search box

**Comment by clelland** [comment]
Looking at the data model, I don't think that we have any way to answer the question "what's in milestone X?". A feature could be added behind a flag in version 50, shipped as an origin trial in 53, and stable in 55, and we would only store the latest status.

As a more real example, https://www.chromestatus.com/feature/5736166087196672 (SVGGraphicsElement.getTransformToElement) is shown as removed in M48, but there is no mention of the fact that it was added sometime around M30.

**Comment by ebidel** [comment]
For progressions like that, owners are supposed to use the comments. We could also beef up the data model to support the full lifecycle of a feature. Might not be worth it though. I defer to Blink engineers :)
