### ISSUE TITLE
JavaScript error with dropdowns

### ISSUE THREAD

**Issue by lukewarlow** [GoogleChrome/chromium-dashboard#3137]
**Guide UX Feedback**
When editing a feature most of the dropdowns are broken.

![image](https://github.com/GoogleChrome/chromium-dashboard/assets/32498324/f2659140-877b-4fe4-b03f-82bd8a91e0d1)

```
Uncaught (in promise) ReferenceError: process is not defined
    at computePosition$1 (floating-ui.core.mjs:88:7)
```

![image](https://github.com/GoogleChrome/chromium-dashboard/assets/32498324/9cbd5f54-72ff-4488-841b-d2c9c629a62d)

**Comment by lukewarlow** [comment]
Opening dev tools and running the below code "fixes" the issue.

```js
process = {
    env: {
        NODE_ENV: "PRODUCTION"
    }
}
```

**Comment by jrobbins** [comment]
I'm sorry for letting this bug through, especially since it blocks users from doing work on the site.

It looks like it got through our release candidate testing because we allowed in some late library changes and tested a slightly different version on our staging server than what was deployed to our production server.  

Thanks for the bug report and the work-around.  

I have deployed it to our production server and it seems to be working now.

**Comment by lukewarlow** [comment]
Would sure be nice to just be able to use popover attribute and CSS anchor positioning. Some day soon maybe! 😄 

No worries. Glad the workaround helped!

**Comment by jrobbins** [comment]
I'll keep this issue open until a better fix is merged and deployed.

**Comment by jcscottiii** [comment]
Related issues about floating-ui:

- https://github.com/floating-ui/floating-ui/issues/1506
- https://github.com/floating-ui/floating-ui/issues/1575

The first one has some linked implementations to resolve it. However, I'm not sure what changed as to why it's needed now.

**Comment by jrobbins** [comment]
Upgrading all of our npm modules, including floating-ui, seems to have resolved the problem.
The work-around has been removed.
These changes were deployed to chromestatus.com yesterday.
