### ISSUE TITLE
Simplify features.json schema

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#321]
https://www.chromestatus.com/features.json has grown out of control as we've added stuff over the years. Here's a proposal for a new schema that:
1. consolidates browser-specific info under "browsers"
2. uses small keys (smaller response!)
3. This restructuring means downstream clients (ie status page etc) do less fix up and can discard entire sub objects they don't care about. 

Additionally, we could remove `null` fields from the server's response. This will make the response even smaller #perfmatters.

We should also version the URL (e.g. `features_v2.json`) so consumers can migrate at their own pace.

```
{
  "id": 6021353392046080,
  "name": "CSS Flexbox: New intrinsic size algorithm",
  "category": "CSS",
  "summary": "The CSS Flexbox specification changed the algorithm for calculating a flexbox's intrinsic size (see below for the spec link...",
  "created": "2015-08-05 22:40:46.897000",
  "comments": "",
  "standards": {
    "spec": "https://drafts.csswg.org/css-flexbox/#intrinsic-sizes",
    "status": { // was standards_str
      "text": "Editor's draft", "val": 4,
    },
    "visibility": "Only a very small number of web developers will care about",
    "footprint": 4,
  },
  "updated": {
    "when": "2015-08-05 22:40:46.897540", // was updated
    "by": "cbiesinger@chromium.org" // was created_by
  }
  "resources:": {
    "samples": [], // was sample_links
    "docs": [], // was doc_links
  },
  "tags": [ // was search_tags
    "Flexbox", "flex"
  ],
  "browsers": {
    "chrome": {
      "bug": "http://crbug.com/240765",
      "owners": ["cbiesinger@chromium.org"], // was owner
      "experiment": false, // was experimentalframework
      "prefixed": false,
      "flag": false,
      "first_of_milestone": true,
      "status": {"text": "No active development", // was impl_status_chrome, "val": 1},
      "desktop": null, // was shipped_milestone
      "android": null, // was shipped_android_milestone
      "webview": null, // was shipped_webview_milestone
      "ios": null // was shipped_ios_milestone
    },
    "opera": {
      "desktop": null,
      "android": null, // was shipped_opera_android_milestone
    }
    "ff": {
      "view": {"text": "Public support", "val": 3, "url": "https://bugzilla.mozilla.org/show_bug.cgi?id=1055887" /* was ff_views_link */}
    },
    "edge": {
      "view": {"text": "No public signals", "val": 5, "url": null /* was ie_views_link */}
    }
    "safari": {
      "view": {"text": "No public signals", "val": 5, "url": null /* was safari_views_link */}
    },
    "webdev": {
      "view": {"text": "No signals", "val": 5}
    }
  }
}
```

**Comment by RByers** [comment]
I like the idea of overhauling the schema.  If it's not too much work to do (with some shim to support the old format for existing clients), then sounds good to me.  But if it's a substantial undertaking then I'd suggest we put it off for a bit and try to couple it with a larger / more impactful effort.  Eg:

1. It seems there is support from at least some other vendors to have a shared database here, rather than trying to each sync/merge eachother's data.  Maybe we should spin up a separate open source project to do that and get consensus between vendors on the right schema?
2. Should we be planning now for the database to be growing big enough that the UI would never want to suck down the whole thing at once?  And instead expose a query API?  For context, our current JSON is about 1MB (161 kB gzipped).  Doesn't seem too crazy to plan for that to grow 10x over the next few years (especially as we do more and more work incrementally as small "features").  That's probably still small enough that worying about a query API is overkill, right?

Regardless, feedback on the above schema:

- Why is `visibility` a string but `footprint` is an integer.  Similarly some things still use duplicate enums+strings (text/val for the different vendors).  Should we just standardize on only strings everywhere for enumerations?
- Perhaps we should separate the concept of vendors into engines + browsers to try to address some of the problems we've been having confusing the two?  Eg. "chromium" (or "blink") is one engine with one feature policy with a variety of browsers that typically (but not always follow) - Chrome desktop, Opera mobile, WebView, Samsung browser, etc.  Similarly, we can't say much about "Safari" until a feature has shipped, but we can talk about plans for "WebKit" and "Safari Technology Preview".  The main thing that matters in launch decisions is the status in the big engines (EdgeHTML, Gecko, WebKit and chromium), while after features have shipped the thing developers care about is what browser versions actually support it.
- @clelland is adding monorail component to the data schema for Chrome.  Maybe we should just have a "bug filing link" for each engine?
- webdev should take an optional list of URLs as well (kind of useless today without this IMHO)

**Comment by RByers** [comment]
On the issue of enums and size, perhaps to avoid unnecessary client memory usage we should just use integers?  It [looks like](http://jsbin.com/budifo) V8 at least does not do string interning, so each copy of the string is using up separate heap memory.

**Comment by clelland** [comment]
The "bug filing link" is a bit more complicated; at least the way I've tried to do it for Chromium, because of components and blocking launch bugs. Maybe we can encapsulate the logic for other engines' bug-reporting systems in the same way, but we may want more than just a string URL for each.

**Comment by jacobrossi** [comment]
### Shared data versus separate repo

I'd prefer keeping them separate, actually.  That allows us to more easily control rolling out features onto our dashboard. Some cases we differ what spec we point at (sigh). Sometimes we change the name/title a bit to clarify differences in our implementation. Each vendor probably wants to have its own extensions to the data that aren't relevant to others (e.g. we don't have "experiments" at the moment). And many other things where the data might differ (and we don't want the data repo to be the place where those fights get fought ;-)). 

But coordinating on common schema is nice.  This is the subset of what's above that I think is mostly common between the various places that use this type of data. So this is the set I'd focus on:

````
{
    id: //Int: happy to continue using the ChromeIDs here
    name: //String
    summary: //String
    category: //String, need to list the possible values out somewhere
    tags: //String: comma-separated
    spec: {
        name: //String: friendly name
        link: //String: URL to spec
        organization: //String (W3C, WHATWG, IETF, ECMA)
        status: //String: need to list the values out
    }
    docs: { //I think we all contribute to MDN
        mdn: //String: URL to doc
    }
    browsers: {
        chrome: {
            status: //String: (Not Currently Supported, In Development, Shipped, Deprecated)
            link: //String: URL to tracker
            experimentalVersion: //Int: version/build number that the feature is available in but requires either prefix, flag, or experiment
            stableVersion: //Int: version/build number that the feature is available by default (no prefix/flag/experiment needed)
        }
        edge: {
            status:
            link:
            experimentalVersion:
            stableVersion:
        }
        firefox: {
            status:
            link:
            experimentalVersion:
            stableVersion:
        }
        safari: {
            status:
            link:
            experimentalVersion:
            stableVersion:
        }
        opera: {
            status:
            link:
            experimentalVersion:
            stableVersion:
        }
    }
}
````

You'll notice this is missing the subjective aspect of the status (in favor / not in favor /priority / etc.).  It might make sense to split that out as a separate "views" string for each browser. So "status" becomes the objective bit about the implementation (and here I'm considering anything prefixed/flag/experiment as still In Development) and "views" becomes the bit that adds subjective color. That enables, for example, a vendor to have a "not in favor" view about an API that shipped amongst other things. 

### Single DB vs Query API

From our perspective, a query api isn't necessary.  We just suck this in as a part of a job on the server. So we're not hitting a 1MB file every page load or anything like that.

### Separate concept of vendors/engines

No, I like being able to differentiate Opera and Chrome, for example, because the version numbers that the platform features ship in can sometimes differ. Sometimes there's work integrating a feature into the browser UI that delays it from shipping. Etc.

**Comment by RByers** [comment]
### Shared data versus separate repo

> I'd prefer keeping them separate, actually.

Can we chat about this in person when I come visit?  I think all the reasons you give are bugs that ultimately are bad for web developers and ideally long-term we'd work towards solving.  From the perspective of a web developer, they should be able to reason about the platform as a set of features (with some level of availability given their user base) without having to resort to reasoning per-browser except in the edge cases (failure modes).  Eg. caniuse.com is ultimately more popular / useful to developers than any of our individual dashboards (and wouldn't work at all if the feature names were different per browser).

But regardless for the purposes of this bug, even if Microsoft isn't interested in collaborating on a common database, sounds like Mozilla may be(/cc @miketaylr).  So we should still consider whether it's worth switching schema's separately from exploring that or not.

### Separate concept of vendors/engines

> No, I like being able to differentiate Opera and Chrome, for example, because the version numbers that the platform features ship in can sometimes differ. Sometimes there's work integrating a feature into the browser UI that delays it from shipping. Etc.

For sure!  I'm not at all suggesting you shouldn't be able to differentiate.  Just that Opera really isn't any different in this regard from Android WebView, Samsung Browser, Chrome Android vs. Desktop, etc.  In all cases there's a joint launch approval process - if Opera thinks an API is bad for the web (or bad for their code base) that goes into our "intent" process where the outcome is a single yes/no decision for he chromium project.  Downstream from that process there's the question of if/when a feature will make it into a particular browser release, but that's entirely different from the policy question of "does the project support this feature".

Anyway I don't think there's a huge difference here in practice.  Either we have a single-level list as you've proposed and have to add a bunch more special cases like "Android WebView" with some UI that knows about the suitable defaults / inheritance policy (i.e. we don't want to ask blink engineers to explicitly separately specify the Opera status - 99% of the time it's the same as Chrome, so blink engineers should usually specify a policy once under a browser-neutral term like "chromium").  Or we have a multi-level list like I describe where the inheritance policy is explicit in the schema.  Either works fine for me.

**Comment by jacobrossi** [comment]
> Can we chat about this in person when I come visit

You bet!

> Downstream from that process there's the question of if/when a feature will make it into a particular browser release, but that's entirely different from the policy question of "does the project support this feature".

I think this gets into the subtle differences between status.microsoftedge.com and chromestatus.com. Ours is more intended to be targeted for developers and the question they're interested in is whether it has landed (or is on the way) for a specific browser, not engine.  We don't use status.microsoftedge.com as the vehicle for driving engineering policy/processes.  Hence, I care more about detailing the browser status than detailing the engine status. But happy to make it work for both use cases.
