### ISSUE TITLE
Feedback re: approval gates documentation

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/chromium-dashboard#3275]
The UI has the following gates, in this order: Privacy, Security, Enterprise, Debuggability, Testing, API owners

![](https://github.com/GoogleChrome/chromium-dashboard/assets/81942/9cfaa2ed-44fa-44b4-9616-5b3852b07559)

However, the documentation at https://github.com/GoogleChrome/chromium-dashboard/wiki/Overview-of-Review-Gates lists Privacy, Security, Debuggability, Enterprise, API Owners. That is, Enterprise and Debuggability should be swapped, and “Testing” should be added following Debuggability.

In addition, I wanted to suggest to link to https://goo.gle/devtools-checklist in the Debuggability section.

**Comment by Jayabsts** [comment]
I don't have a enterprise. Why are text messages coming to my device? My device has been acting up Every since chromeuim made changes. My background color is always black or gray. I use to get messages when I changed sim color.  Do you see any reason why text messages wouldn't be arriving at my device? Has the string been affected? Please allow all notification to come to my device normal. Remove the feature that's stopping popups. I want all messages to my device. Why do they have to filter through post messages? If there is any certificate or documents needed. Please let my know. I'm not a organization or any of that nonsense. Just trying to fix my device

**Comment by Jayabsts** [comment]
Please help me. My number shows 1 ***-***-**** on my sim card, but good has number showing (404) 512-7737. When I changed contact number to show all together. No spaces. A text messages came through. Who's responsible for thread or string. Please you guys

**Comment by Jayabsts** [comment]
How do I fix server error 255? Can someone please respond. I'm now using device. No text message or calls are reaching my device.

**Comment by Jayabsts** [comment]
![Screenshot_20230830-082852](https://github.com/GoogleChrome/chromium-dashboard/assets/143570143/689308a6-476e-4062-88ba-4836cfabacca)

**Comment by Jayabsts** [comment]
![Uploading Screenshot_20230830-082838.png…]()

**Comment by Jayabsts** [comment]
![Screenshot_20230830-082207](https://github.com/GoogleChrome/chromium-dashboard/assets/143570143/b21d37ff-fe4c-441c-8576-65737bcde99b)

**Comment by Jayabsts** [comment]
How do I create path for incoming messages?

**Comment by jrobbins** [comment]
> How do I create path for incoming messages?

This issue is just for the specific topic in the summary.  Please don't post off-topic comments.

**Comment by jrobbins** [comment]
> Enterprise and Debuggability should be swapped, and “Testing” should be added following Debuggability.
> In addition, I wanted to suggest to link to https://goo.gle/devtools-checklist in the Debuggability section.

I made these fixes to the docs.  Thanks for pointing out the problems.
