### ISSUE TITLE
Add "Prefixed" to list of potential vendor statuses

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/chromium-dashboard#336]
At a minimum, Edge's public data reports shipped-but-prefixed features. We should be able to report this as a status for any vendor.

**Comment by RByers** [comment]
Yeah, I was a little concerned with implying that a browser shipping some prefixed version of an API was really the same "all green" from a consensus perspective as them shipping the standard API.  There can be substantial design differences between prefixed and standard versions of an API.

I can even imagine cases, for example, where Edge is explicitly opposed to the state of a standard for an API that they've already shipped a prefixed version of (perhaps because the standard changed substantially from their design - eg. snap points).  Then again, in such a case Edge should just have a 2nd status entry for the new standard API and our status should reflect that, ignoring the prefixed one.  So perhaps it's fine to just treat "preifxed" as "shipped" when the IDs match and rely on the IDs not matching for these special cases where the APIs are really different.

@jacobrossi any thoughts?

**Comment by ebidel** [comment]
In theory, new features will not be prefixed. Right? This only applies to older stuff.

We've tried to stay clear of adding too much vendor detail to chromestatus. The thought is that other sites like caniuse.com do a better job and give developers the info they need. 

However, we care about "browser consensus" for each features. "Shipped / prefixed" as been the same thing in regards to the consensus calculation (color of each feature). If we add "Prefixed" as another consensus status, we need to think about what that means in the calculation.

@RByers Agreed. I think the intention is that matching IDs are the same feature. Any deviations can just get a new entry. For example, Blink engineers have been creating [separate entries for unprefixing](https://www.chromestatus.com/features#unprefixed).

https://www.chromestatus.com/features/5452478162141184 is another good example of one of these cases. Edge is opposed to the FS API as-in Chrome but are supportive of the newer one. We changed our entry to include "Filesystem API (Chromium)" so it was clear on each dashboard.

**Comment by RByers** [comment]
See Jacob's comments: https://github.com/GoogleChrome/chromium-dashboard/issues/335#issuecomment-232713311

Basically - prefixed should be "in development" (i.e. experimental) - similar to the way we'd treat an origin trial or available behind a flag.  I think that sends the same message (support for solving the problem, has code, but API shape not necessarily final).

**Comment by jacobrossi** [comment]
FWIW, we intentionally separate this from "in development" because developers can try it out. From a web dev's perspective, that's different. Even in regards to Blink's intents process, this really is a different signal as the existence of a prefixed API potentially affects the compatibility implications of shipping the API.

Just a thought. I don't necessarily object to you mapping prefixes to in development if that's what you prefer.  As I said in the other comment linked above, we'll probably collapse prefixes/flags/experiment into one status called Experimental. TBD.

**Comment by RByers** [comment]
Agreed, we're hitting up against a deeper problem with the asymmetry between how we talk about our own status and that in other browsers.  A different proposal: #338.
