### ISSUE TITLE
Starred features are shown *below* "features I can edit"

### ISSUE THREAD

**Issue by cbiesinger** [GoogleChrome/chromium-dashboard#3404]
**Is your feature request related to a problem? Please describe.**
On https://chromestatus.com/myfeatures, starred features are listed at the bottom, the top shows "features I can edit". Since starring a feature is a much stronger indication that I am interested in it, and because the list is likely shorter, it seems like it would make more sense to show starred features first.

**Describe the solution you'd like**
Show the "starred features" section above the "features I can edit" section

**Additional context**
n/a

**Comment by jrobbins** [comment]
Ah, I see what you mean.  I had assumed that the "features I can edit" list would be just a few items, but it looks like your list is about 20 items.

Swapping the order of the sections would not help users who have starred a lot of feature entries because that list could be long too.

As a work-around, you could click the right-hand "v" icon for each section to collapse it.  However, you would need to do that each time that you view the page.

I am thinking that a good solution would be to remember the expand/collapse state of each section as a user preference.  Those two sections would default to being open.  But, if you close one, it would be closed on your next visit.

**Comment by cbiesinger** [comment]
that would probably be a reasonable workaround

**Comment by jstenback** [comment]
Could we show the number of items in a section title if it's closed? I.e. "Features I can edit (21)" or something like that, to give a sense of there being content in those sections even if you don't have them expanded?

**Comment by jrobbins** [comment]
This issue is obsolete because we split the myfeatures page into separate pages.
