### ISSUE TITLE
Edit mode UX is confusing

### ISSUE THREAD

**Issue by syg** [GoogleChrome/chromium-dashboard#3504]
I find it very confusing that in a feature that you own, stages are editable even without clicking on the pencil icon up top.

Outside of "pencil mode", note how there is an "Edit fields" button:

![Screenshot from 2023-11-15 13-25-32](https://github.com/GoogleChrome/chromium-dashboard/assets/95697/dc5a448f-88a8-46c2-af51-8d14ca266b85)

In "pencil mode", there is now an "Update" button as well as an "Edit" link:

![Screenshot from 2023-11-15 13-26-26](https://github.com/GoogleChrome/chromium-dashboard/assets/95697/2eaddded-f96e-44e4-ac81-1b306ef3e7aa)

In particular, I was looking for the link to generate an intent email, which was only available in pencil mode, and was fooled into thinking I was already in pencil mode because the button outside of pencil mode, which I guess is officially called "Edit mode", says "Edit fields".

**Comment by jrobbins** [comment]
I agree it is confusing.  We are in the process of phasing out the old "pencil mode" (Guide UX) and it has taken a long time because of other tasks.  Thanks for the reminder that people are still using the older page because some options are only there, and because they more used to it.  I hope to finish the transition in the smoothest way possible for users.

**Comment by jrobbins** [comment]
"Pencil mode" is gone.  Now there is only the "Edit fields" buttons on each stage.
