### ISSUE TITLE
OT creation does not work as intended, pre Chromestatus-OT automation

### ISSUE THREAD

**Issue by KyleJu** [GoogleChrome/chromium-dashboard#3910]
Mike mentioned that  the "request trial creation" button is missing for https://chromestatus.com/feature/5723617717387264.

More context:
We renamed DisableThirdPartyStoragePartitioning to DisableThirdPartyStoragePartitioning2 ([CL here](https://chromium-review.googlesource.com/c/chromium/src/+/5560064))

Panos also pointed out:

After some digging I see several confusing things and I suspect this highlights a number of bugs that we need to fix:
1. I didn't see any email notifications to o-t-support for the DisableThirdPartyStoragePartitioning and DisableThirdPartySessionStoragePartitioningAfterGeneralPartitioning [requests](https://chromestatus.com/admin/ot_requests#) that you made. 
2. Somehow the new trial stage for DisableThirdPartyStoragePartitioning2 is associated with the wrong [thing](https://developer.chrome.com/origintrials/#/view_trial/3444127815031586817) (click the View Origin Trial button to verify). The first trial stage is still associated with the right [thing](https://developer.chrome.com/origintrials/#/view_trial/-8517432795264450559).
3. I had suggested changing the trial name, but maybe I wasn't very clear that I meant only changing "origin_trial_feature_name", [not "name" too](https://chromium-review.googlesource.com/c/chromium/src/+/5560064/6/third_party/blink/renderer/platform/runtime_enabled_features.json5#1256). Perhaps this is somehow related to (2) above?
4. Both of the old trials were associated with the same Chromestatus feature, even though the feature didn't have two separate OT stages. Maybe this also contributes to (2).

Not seeing the extension in the trix is expected, OT extensions are now handled automatically by the system, but OT creations aren't yet.

**Comment by KyleJu** [comment]
Note to myself: Suspect the number 2 is the cause

**Comment by DanielRyanSmith** [comment]
This has happened because both "DisableThirdPartyStoragePartitioning" and "DisableThirdPartySessionStoragePartitioningAfterGeneralPartitioning" link to the same Chromestatus feature, and the OT [association script](https://github.com/GoogleChrome/chromium-dashboard/blob/main/internals/maintenance_scripts.py#L236-L458) made the assumption that the newly created OT stage that had no associated origin trial ID was supposed to be associated with this origin trial stage.

In order to mitigate this, something needs to be clarified:
- Should the "DisableThirdPartySessionStoragePartitioningAfterGeneralPartitioning" be shown as an OT stage on this Chromestatus feature?
  - If so, we could create an additional OT stage via the "Add Stage" button on the Chromestatus feature and associate it manually (update the `origin_trial_id` value on the stage entity in the database) with the "DisableThirdPartySessionStoragePartitioningAfterGeneralPartitioning" origin trial.
  - If not, we need to find some feature to associate this "DisableThirdPartySessionStoragePartitioningAfterGeneralPartitioning" origin trial with, then manually remove the `origin_trial_id` value for the stage labeled as "DisableThirdPartyStoragePartitioning2". The value of the Chromestatus link in the OT database is also linking to the incorrect Chromestatus feature, and needs to be updated.

This is yet another problem that the CS-OT integration work should alleviate in the future.

**Comment by DanielRyanSmith** [comment]
This issue can feasibly be closed if no one sees anything else that is not correct. View the comment above for the steps taken to mitigate.

**Comment by past** [comment]
Apart from the 3 trial stages not being in the order of trial creation, I no longer see anything wrong with the setup. Thanks for jumping on this Daniel!

Assuming that it's not straightforward to just rearrange the stages, I'm closing this. Please reopen if this can be done ~trivially.
