### ISSUE TITLE
Q. why is usage metric for CSP in decline?

### ISSUE THREAD

**Issue by publicarray** [GoogleChrome/chromium-dashboard#437]
As far as [I know](https://scotthelme.co.uk/alexa-top-1-million-crawl-aug-2016/#previousscans) [more websites](https://trends.builtwith.com/docinfo/Content-Security-Policy) have enabled a CSP and I was hoping someone at the chrome team can shed some light on why https://www.chromestatus.com/metrics/feature/timeline/popularity/15 shows a steep decline in usage. I realize that there is probably not a simple answer but I thought I could try asking anyway.
Chrome does have a large install base, maybe for the metrics it could be useful to get the sample number per graph or the number of websites over time in addition to the percentage? just a thought.

**Comment by publicarray** [comment]
cc @ebidel

**Comment by ebidel** [comment]
We can only expose the "% of page loads" that use the feature over time. Unfortunately, we can't share raw # of sites or sample size.

I'm not entirely sure why the graphs have been steadily going down since last year. One explanation is that, while the number of folks using CSP is growing, chrome's install base is also growing. It's also possible the way we're recording certain metrics like this internally has changed over the course of time.

**Comment by publicarray** [comment]
Thank you for your swift reply. That's unfortunate but understandable. I just wanted to try to get to the bottom of this.

That is a plausible explanation but I remain a little sceptical.

Personally I think the timelines are useless for web developers. They may have a purpose for the chrome dev team but even then I think the graph can be misleading.

Anyway, Thank you for your time.

**Comment by simevidas** [comment]
> One explanation is that, while the number of folks using CSP is growing, chrome's install base is also growing. IOW, the number of pages chrome loads is increasing faster than the number of pages that use the feature. Since those graphs show percentages, the "% of chrome page loads that use this feature at least once" is dropping b/c the denominator is getting bigger over time. 

I’ll try to explain why I think this is not correct.

A larger install base has lead to a larger number of page loads, but all these page loads are still “operating” on the same websites as before, and thus should not affect the CSP usage percentage. 

For instance, if 2–3 years ago 20% of page loads used CSP, this was the result of Chrome users visiting the websites that were available on the web. Now, a few years later, we have a bunch of new users (larger install base) and these new users are generating additional page loads, but thee loads are still operating on the same websites as before. 

Since the percentage *did* drop, this means that the users are now visiting a different range of websites. For instance, it is expected that the new users are coming from developing countries and are visiting local websites. These websites may not be as quick in adopting features like CSP. 

This is just one theory, but whatever factor or combination of factors influenced the percentage, the number of page loads was not one of those factors.

**Comment by ebidel** [comment]
I'm kinda confused by your explanation. This:

> these page loads are still “operating” on the same websites as before

contradicts this:

> Since the percentage did drop, this means that the users are now visiting a different range of websites

---

Something like `<form>`, [window.open](https://www.chromestatus.com/metrics/feature/timeline/popularity/475), and [window.event](https://www.chromestatus.com/metrics/feature/timeline/popularity/69) are interesting because all have been around forever, yet all are on the decline. I'd expect really old stuff like that to see an uptick over the years...even as emerging markets come online. But that's not the case.

But yea, I think we're saying the same thing, only slightly different :)  I suspect there are a few different reasons that could contribute to the declines but it's hard to pinpoint exact reasons when there are so many variable at play.

**Comment by simevidas** [comment]
Yeah, my wording in that sentence was confusing.

I meant, if we assumed, for the sake of argument, that the users were still visiting the same sites as before, the larger install base would not affect the percentage. In other words, 1 million or 100 million users should produce the same percentage if they visit the same sites.

A percentage drop can only be the result of a change in the range of pages that are included in the sample, not the size of the sample by itself. At least, that’s as far as my logic goes, but I agree, there are many variables at play, and, on the surface, it’s quite puzzling.
