### ISSUE TITLE
Highlight outdated feature entries for upcoming releases

### ISSUE THREAD

**Issue by KyleJu** [GoogleChrome/chromium-dashboard#4370]
The goal is to notify/incentivise feature authors to keep features up-to-date in the upcoming releases:

- All features on the roadmap page are included in upcoming releases, so need to be up-to-date.
- There are also features missing in the roadmap page, but still in upcoming releases. They also need to be up-to-date

### Proposed solution
Show a different UI treatment for stale features vs. up-to-date ones. Differentiate the message/color intensity between feature owner view and public view.

It can take advantage of the `last updated` field in feature entries and highlight a different UI, when `current_time - last_updated < a certain threshold`  (e.g. 1 week) and `milestone_date - current_time < e.g. 1 week and > 0` :
![Screenshot 2024-09-16 2 01 26 PM](https://github.com/user-attachments/assets/f3b0a9fe-9e51-46c1-86e2-28ff38a0df78)

The out-of-date feature entries will be highlighted on the roadmap page and feature entry page:

E.g. a mock UI on the roadmap page, public view:
![Screenshot 2024-09-16 2 06 19 PM](https://github.com/user-attachments/assets/5f2d2878-7706-46b3-8153-60e18f4981b1)

e.g. a mock UI on feature page, public view:
![Screenshot 2024-09-16 2 10 07 PM](https://github.com/user-attachments/assets/6922e82f-fee6-4ca1-a34b-9a7ea3897740)

### Questions
Potential questions for UI - a different color on the roadmap and feature entry page when the view is the feature author. What about highlighting them in red?

Questions to @jyasskin:
- How to find features that are missing from the roadmap page, but included in the upcoming releases?
- How far should we highlight? e.g. the future 3 milestones?
- What is the threshold for "outdated" features?
- Do we only highlight outdated features that has not been shipped (upcoming releases)? What about the shipped features and what is the threshold for shipped features

**Comment by KyleJu** [comment]
Potentially, if a feature doesn't need any update, the author can leave an "up-to-date" comment. It will update the timestamp

**Comment by past** [comment]
Note that we have a few more issues that similarly aim to get feature owners to respond to notification emails and therefore keep features up to date (#4354, #4355, #4356). I think it makes some sense to use the same "freshness" threshold for the highlighting you propose in this issue as the threshold we use to decide when to send those notification emails.

**Comment by jyasskin** [comment]
The `updated` field probably isn't the one to use for this, since it would treat a feature as completely up-to-date if any field is modified. There's also the `accurate_as_of` field, which is what gets updated when people click the right buttons from the reminder and escalation emails.

https://github.com/GoogleChrome/chromium-dashboard/blob/6b7e6aa291449bd0d5c30bd79fd7f5ac6cfad813/internals/core_models.py#L74-L75

As part of this, it should be easier for a feature owner to mark a feature accurate once they check the feature's fields.

Re the questions:

#### How to find features that are missing from the roadmap page, but included in the upcoming releases?

I don't think this question needs to be answered for this feature, but if someone's sent an I2S and their shipping milestone isn't set to an upcoming milestone, that's something to flag. I think the API owners usually notice this though.

#### How far should we highlight? e.g. the future 3 milestones?

I think this is implied by where the UI lives. The roadmap shows the next 2-3 milestones by default, so highlighting on the roadmap will emphasize those milestones. But if someone navigates along the roadmap, and a feature in a more distant milestone hasn't been marked as accurate since the threshold, it should also be highlighted.

The feature pages should highlight if they're inaccurate no matter how far in the future they're planned to ship. The thresholds might be somewhat different, but if a feature hasn't been checked in 6 months, people stumbling on it should know not to trust it.

#### What is the threshold for "outdated" features?

As @past said, this should be consistent with the threshold in https://github.com/GoogleChrome/chromium-dashboard/blob/6b7e6aa291449bd0d5c30bd79fd7f5ac6cfad813/internals/reminders.py#L223-L226
That is, if a feature's scheduled to ship in the next 2 milestones, and its `accurate_as_of` date is at least 4 weeks ago, it should get flagged as untrustworthy. 

For a feature that isn't shipping soon, I suspect that 4 weeks is too tight. As a guess, maybe 8 weeks for a feature that's going to origin trial or dev trial in the next 2 milestones, and 3-6 months for a feature that doesn't have any upcoming transitions? We'll probably need to update these thresholds based on feedback after this is launched.

#### Do we only highlight outdated features that has not been shipped (upcoming releases)? What about the shipped features and what is the threshold for shipped features

If something is shipped, and its `accurate_as_of` is before the stable date for the milestone it shipped in, I think we should keep warning readers that it might not actually have shipped, and prompting the feature owner to verify the feature. If `accurate_as_of` is after the stable date, it should count as up-to-date forever. 


Does that all make sense?

**Comment by past** [comment]
One thought I've mentioned to Kyle is that the UI treatment for stale entries in the roadmap page should be less invasive (maybe an additional icon?) than the one in the feature details page. There can be many reasons for a user to view the roadmap page where the entries' staleness isn't very relevant, but we should at least ensure the details page gives feature owners enough of a nudge to update their entry.
