### ISSUE TITLE
Searching appears to be case sensitive

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#4518]
**Describe the bug**
I am trying to find the [tabbed web apps](https://chromestatus.com/feature/5128143454076928) feature. I searched for [tabbed](https://chromestatus.com/features?q=name%253Dtabbed) and the results came up empty. The same thing happened when searching for [tabbed web apps](https://chromestatus.com/features?q=name%253D%2522tabbed%2520web%2520apps%2522). The search succeeds only with [Tabbed web apps](https://chromestatus.com/features?q=name%253D%2522Tabbed%2520web%2520apps%2522), but not with say [Tabbed Web Apps](https://chromestatus.com/features?q=name%253D%2522Tabbed%2520Web%2520Apps%2522).

Of course searching is useful primarily when one doesn't know the precise capitalization (or spelling) of a feature's name.

**Comment by jrobbins** [comment]
The first one is not an issue with case-sensitivity.  It is instead an unintuitive difference between the `=` operator and the ':' operator.   The `=` operator only matches a whole field value.  Whereas, the `:` operator matches words within a field.

The second and third examples do seem like a bug.  I'll make sure to make those case-insensitive.

**Comment by jrobbins** [comment]
Actually, making the = operator case-insensitive is not that easy because it is translated into a NDB condition and NDB is case-sensitive.

Maybe what we should do is have the autocomplete menu offer `:` for string fields.  I think that the `:` operator behavior is more what people are expecting.  I would need to convert `:` to `=` for numeric fields, but that seems straightforward.   Also, the help text needs to explain the meaning of the search operators.

**Comment by past** [comment]
That is indeed surprising, and it's not even described in the help interstitial dialog. What you suggest sounds good to me, if I understand you correctly: only surface `=` or `:` in the UI, not both, but use the right one under the hood depending on the type of the field.
