### ISSUE TITLE
Developer trial stage needs dedicated start and end fields

### ISSUE THREAD

**Issue by ricea** [GoogleChrome/chromium-dashboard#453]
Feature "WritableStream" https://www.chromestatus.com/feature/5928498656968704 is behind a flag and has been since milestone 56. So I thought I'd change the listed milestone to 56, except when I go to edit it I see the following text:

"Chrome for desktop: First milestone the feature shipped with this status (either enabled by default, origin trial, intervention, or deprecated)"

The feature is none of "enabled by default, origin trial, intervention, or deprecated", which maybe means that the field should contain the expected release milestone (ie. 59)? It's unclear.

**Comment by jpmedley** [comment]
We have currently have separate fields for dev trial, origin trial, and shipping, meaning we can show all simultaneously. Sometimes removal of a dev trial flag lags shipping of a feature, not because the dev trial is still going on, but because the logistics of removing the flag mechanics vary from feature to feature. Shipping of a feature means the dev trial is over whether the flag is there or not. No end field will be provided.
