### ISSUE TITLE
Usage chart: bars are scaled to highest fraction, instead of 100%

### ISSUE THREAD

**Issue by bakkot** [GoogleChrome/chromium-dashboard#531]
[Here](https://www.chromestatus.com/metrics/feature/popularity), I expect a bar labeled "78.934111%" to be about 79% full, not 94%.

<img width="768" alt="screen shot 2018-01-26 at 3 25 51 pm" src="https://user-images.githubusercontent.com/1653598/35464935-a7461400-02ad-11e8-9f7b-8d27dbabcf9d.png">

**Comment by ebidel** [comment]
This was intentional so some of the lesser used features actually show a bit of bar.

**Comment by eakuefner** [comment]
Sorry, just a drive-by, but I think this might not be the best fix for the "bars-too-small" problem, since it produces a classic example of a [misleading graph](https://en.wikipedia.org/wiki/Misleading_graph). On my widescreen Mac monitor, I see many hundreds of pixels of blank space to the right of the bars; how about just extending the bars instead?

**Comment by ebidel** [comment]
Extending them to where though? I don't think it's good to make users have
to scroll the viewport.

The bars don't add much value to begin with. Mostly just meant to be a
visual relative indicator of the usage when glancing at the list.
