### ISSUE TITLE
Feature popularity stackrank chart looks wrong

### ISSUE THREAD

**Issue by nyaxt** [GoogleChrome/chromium-dashboard#545]
https://www.chromestatus.com/metrics/feature/popularity says that the most popular feature implemented in Chromium is CSSSelectorWebkitProgressBar with 1.36%.
However, [CookieGet](https://www.chromestatus.com/metrics/feature/timeline/popularity/2195), which is used in >85% of the websites doesn't appear in the stackrank.

**Comment by ebidel** [comment]
Weird. These are back for me:

<img width="1046" alt="screen shot 2018-04-02 at 8 41 18 am" src="https://user-images.githubusercontent.com/238208/38202740-a39a3214-3651-11e8-82e8-19f972ce868f.png">

We didn't make any changes to the site overnight :) Maybe there were backend issues with GCP and the datastore.

**Comment by ebidel** [comment]
Please reopen if you see this again.

**Comment by ebidel** [comment]
From reading blink-dev threads, looks like metrics where changed from under us. Reopening until we figure out what's going on.

The % are also over 100% :(

**Comment by clelland** [comment]
cc: @loonybear -- in case this is related to recent UseCounter changes in Blink.

**Comment by loonybear** [comment]
Yea sorry about that. The % over 100% thing should have been fixed and rolled out soon (M67).

**Comment by ebidel** [comment]
Thanks @loonybear. Guess we'll keep this open and watch for m67 to hit stable. Hopefully this fixes itself.

**Comment by phistuck** [comment]
@ebidel and @loonybear - those percentages are feeding investigations and decisions on Blink intents, can a fix be merged, or can something else be done so that the numbers would be trustworthy?

**Comment by loonybear** [comment]
Most features are still being reported correctly. 
Big feature usage shift was due to a few bugs that caused the pagevisits being off by 30%. 

Over 100% usage were because features being logged before page commits and they could be a) logged multiple times per page or b) counted even though shouldn't be logged at all (features from a non http/https page or a new tab page or etc). But those features are rare, as most features are logged after page commits. 

We can certainly merge it earlier but I don't think the percentages will be affecting blink intents process much.

**Comment by ebidel** [comment]
@phistuck I'm not worried about a temporary hiccup in a few metrics. Plus, anything that high wouldn't be considered for a deprecation/removal :)

**Comment by phistuck** [comment]
@ebidel - having a few metrics above 100% looks like the tip of the iceberg and makes me (at least) not trust the rest of the result. Other things might have been blown out of proportion as well, but simply did not make it to over 0.1% more than the usual.
This reduces the deprecation/removal opportunities, which sounds like you are against for some reason (I know they can be hard for the few developers that use those features, but they do benefit the platform overall, after all).

**Comment by TakayoshiKochi** [comment]
Getting back here since M67 has been shipped for a few days.
I don't think M67 rolled out to everyone yet, but still, considering the stats are calculated ~24hours there should be some change ...

Screenshot of the stack rank today.

![wuvdw0vetzg](https://user-images.githubusercontent.com/4220972/40895856-abea5166-67ec-11e8-90e0-b83951fb16ed.png)

**Comment by ebidel** [comment]
The numbers that we're pulling from UMA still are inflated. You can see that the entry on 2018-06-01 is still 142%.

<img width="789" alt="screen shot 2018-06-04 at 11 29 28 am" src="https://user-images.githubusercontent.com/238208/40935090-d7f932a0-67eb-11e8-90b3-e8578c8f32c3.png">

@loonybear Are these numbers starting to stabilizing on internal UMA?

**Comment by TakayoshiKochi** [comment]
Any updates?  Today the top-ranking one (SecureContextCheckFailed) is 177% :frowning:

**Comment by ebidel** [comment]
UMA is coming down internally:

<img width="522" alt="screen shot 2018-06-19 at 8 14 17 am" src="https://user-images.githubusercontent.com/238208/41606561-c9546edc-7398-11e8-8827-af4a0521f239.png">

There's a couple of days of delay on our side. We should hopefully start to see better numbers by end of week.

**Comment by TakayoshiKochi** [comment]
Today the top "CleanScriptElementWithNonce" is ~97% (< 100%), so it's fixed now...?

The old top ranked "SecureContextCheckFailed" is ~25% now, down from 177% 10 days ago,
which is a sharp drop.

![image](https://user-images.githubusercontent.com/4220972/42082420-e1a07134-7bc2-11e8-85ed-38a15ccf101d.png)

Shall we ignore the date between Mar. 20 ~ Jun. 15?  And it would be nice we have another note like one for 2017-10-26.

**Comment by ebidel** [comment]
Oh great! Looks like it's corrected itself. I'll leave this bug open as a reminder to annotate the graph.

**Comment by loonybear** [comment]
Hi,

Sorry for the late reply. I was on vacation in the past two weeks.

To confirm the fix. Yes, we landed the fix for that in M67. The results on
chromestatus.com reflects to the records on "dominant" milestone (which is
why the changes are later than when the milestone is rolled out).

And yay. I am glad that everything is finally "correct" again.

There are still minor tweaks I am working on to improve the accuracy of
UseCounter further. So please stay tuned.

Cheers,

Luna Lu | Software Engineer | loonybear@google.com | +1 519 513 5751

**Comment by progers** [comment]
Emil (eae) and I were looking at graphs today and they still seem to be inflated. Should this have been fixed or did this bug surface again?

**Comment by loonybear** [comment]
Hi, could you please list me some features that you think are inflated?

Thanks

Luna Lu | Software Engineer | loonybear@google.com | +1 519 513 5751

**Comment by progers** [comment]
A lot of them are over 100%:
https://www.chromestatus.com/metrics/css/popularity

For example, `display` is reported as being on ~150% of pages:
https://www.chromestatus.com/metrics/css/timeline/popularity/4

**Comment by loonybear** [comment]
Yea, this is expected.

The change for the HTML features are merged a lot earlier than the change
for the CSS properties.

Commit ed9859e0...
<https://crrev.com/ed9859e051fd0175204cbb8a0efb2cefc20790de> initially
landed in 69.0.3457.0


So to wait that change tp be in the dominant version we still need to wait
for a little bit.

Sorry for the inconvenience.


Luna Lu | Software Engineer | loonybear@google.com | +1 519 513 5751

**Comment by progers** [comment]
Thanks for the quick response. If I understand correctly, this will be fixed when M69 is promoted to stable (near the end of this month)?

**Comment by loonybear** [comment]
I would assume so. Yes.

Luna Lu | Software Engineer | loonybear@google.com | +1 519 513 5751
