### ISSUE TITLE
Duplicate Chrome Version on Schedule Page

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#629]
As shown in the image below, sometimes the [schedule page](https://www.chromestatus.com/features/schedule) shows duplicate entries. This is believed to be a consequence of Chrome channels updating in sequence instead of simultaneously. Chrome status should be able to take this into account wen displaying versions. 

![image](https://user-images.githubusercontent.com/8204171/55062917-e0507400-509c-11e9-84a3-2eb9062f3b45.png)

Possible solutions:
* Exclude duplicate versions completely.
* Add appopriate text to explain the duplication.

**Comment by ebidel** [comment]
Yep, this is a direct result of releases across the channels. Sometimes there's a small overlap when a new major milestone lands. The service worker caching on the page can also make it look like things are out of date when they're not. 

FWIW, I never addressed this because the period where there overlap occurs is < 24hrs. Majority of users will never experience the double cersions.

**Comment by jpmedley** [comment]
The rollout of 73 was hung up for a while in mid deployment. This was still showing duplicate at the time I created this ticket yesterday. I'm leaving this open, but changing the priority.

**Comment by jpmedley** [comment]
In case it wasn't clear, when I commented on March 27, Chrome 74 had been duplicated for six days, directly contradicting Eric's assertion that the overlap will be less than 24 hours.

**Comment by jpmedley** [comment]
Doesn't happen any more.
