### ISSUE TITLE
Replace constants in emails

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#769]
Email notifications of entry changes describe changes to implementation status using the integers associated with code constants. Since many people, myself included, don't have the meanings of these constants memorized, it would be better to resolve these to the strings shown on the status entries.

The image below shows what's currently done in emails:

![image](https://user-images.githubusercontent.com/8204171/75366475-a622c000-5873-11ea-8073-488d5ac11db9.png)

**Comment by jrobbins** [comment]
I looked into this a bit today.  It seems possible, but not trivial.   

The way that diffs are currently computed is that a copy of each entity property X is stored as property _old_X in the entity in RAM.  Then, in the put() method, it loops over every property and compares it to the _old copy.  That's all done without taking any property metadata into account, so there is no definition of what enum value to use when the integer is something like 1 or 3.  In fact, all the properties are just IntegerProperties rather than EnumProperties, so there is no clear mapping to human-readable strings in the entity.   The only way that it works in the UI is that the mapping is made in the UI form definition. 

So, one approach I might try is: make a dictionary of {property_name: enum_value_dict}.  This compensates for the lack of using EnumProperty in the existing code.  In __notify_feature_subscribers_of_changes(), I would check if the current property has associated enum values, and if so, use the enum strings instead.

**Comment by jpmedley** [comment]
I've been living with this for years, I guess I can live with it a few more. I would like to keep this open though. Maybe there's another valid reason somewhere to make the dictionary and you could amortize the time cost.

**Comment by jrobbins** [comment]
Sure, let's keep this issue open until it is resolved.  My comments above are just my notes as I work through the problem.

**Comment by jrobbins** [comment]
This has been live for a few days.
