### ISSUE TITLE
Feature popularity is down

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#846]
**Describe the bug**
https://chromestatus.com/metrics/feature/popularity is not loading data

**Comment by jrobbins** [comment]
It seems to be working now.

In the logs I see several periods during the day when that page times out repeatedly, and then it goes back to working again.

I think the underlying cause is that we retrieve that data from our datastore using an inefficient query that contacts the database once for each feature, which is over 3000 times.  We previously worked around it by having it done by a cron task that does not have an execution time limit.  We are probably not keeping the result in memcache long enough, so when there is  a cache miss, the user needs too wait for a new value to be computed, but it never completes because of the timeout.

A quick solution would be to run the cron task more often or increase the length of the memcache lifetime.  A better fix would be to rewrite that query to make it more scalable, or at least incremental so that progress would be made by a request even if it times out.

**Comment by npm1** [comment]
Thanks, it is indeed working for me now.

**Comment by jrobbins** [comment]
This query was rewritten a few weeks ago.
