### ISSUE TITLE
Automate UMA property list

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#97]
The list is manually maintained in uma.py. It should pull from live UserCounter.h/cpp

Possibly from http://src.chromium.org/viewvc/chrome/trunk/src/tools/metrics/histograms/histograms.xml, which is CORs enabled

**Comment by beaufortfrancois** [comment]
@ebidel May I tackle this one?

**Comment by ebidel** [comment]
Totally.

**Comment by beaufortfrancois** [comment]
http://src.chromium.org/viewvc/chrome/trunk/src/tools/metrics/histograms/histograms.xml hasn't been updated for 5 months since chromium switched entirely to Git.

Therefore I think I'll use https://chromium.googlesource.com/chromium/src/+/master/tools/metrics/histograms/histograms.xml?format=TEXT even though it only serves base64 encoded text for now. See https://code.google.com/p/gitiles/issues/detail?id=7 for some background

**Comment by beaufortfrancois** [comment]
WIP at https://github.com/beaufortfrancois/chromium-dashboard/compare/GoogleChrome:master...beaufortfrancois:automateUMA?expand=1

**Comment by ebidel** [comment]
@beaufortfrancois can we close this?

**Comment by beaufortfrancois** [comment]
Yup! Doing it now!
